begin;
-- The deployment builder inserts pending migrations immediately after this role anchor.
set local role postgres;
set local search_path = extensions, public;
create extension if not exists pgtap with schema extensions;
grant usage on schema extensions to authenticated, service_role;
grant execute on all functions in schema extensions to authenticated, service_role;
select no_plan();
create function pg_temp.cid(n int) returns uuid language sql immutable as $$select ('ac300000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
insert into auth.users(id,instance_id,aud,role,email) values(pg_temp.cid(10),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','management-agent@test.invalid');
insert into public.profiles(id,role,name) values(pg_temp.cid(10),'admin','Synthetic admin') on conflict(id) do update set role=excluded.role;
insert into public.teacher_catalogs(id,name,subjects) values(pg_temp.cid(40),'Calendar test teacher',array['영어']);
insert into public.classroom_catalogs(id,name,subjects) values(pg_temp.cid(41),'Calendar test room',array['영어']);
insert into public.classes(id,name,class_type,subject,status,schedule_storage_mode,student_ids,teacher,room,schedule) values(pg_temp.cid(20),'First class','regular','영어','수강','legacy','[]','Calendar test teacher','Calendar test room','월 10:00-11:00');
insert into public.academic_schools(id,name,category) values(pg_temp.cid(1),'Synthetic High','high'),(pg_temp.cid(4),'Other School','middle');
insert into public.academic_events(id,school_id,title,date,type,grade,note,content) values(pg_temp.cid(2),pg_temp.cid(1),'Midterm','2099-10-01','시험기간','고1','KEEP_NOTE','KEEP_CONTENT'),(pg_temp.cid(5),pg_temp.cid(1),'Untouched','2099-12-01','체험학습','all','KEEP_UNMENTIONED',null);
create temp table ev(k text primary key,v jsonb);grant all on ev to authenticated,service_role;
create temp table no_send as select (select count(*) from dashboard_private.notification_events) events,(select count(*) from dashboard_private.notification_deliveries) deliveries,(select count(*) from public.student_class_enrollment_history) enrollments,(select count(*) from public.makeup_request_events) approvals;
select set_config('request.jwt.claim.sub',pg_temp.cid(10)::text,true);
set local role authenticated;
insert into ev values('all',public.create_agent_credential_v2('All management',array['classes:read','class-details:read','class-info:write','calendar:read','calendar:write'],'{}',now()+interval '1 day',true));
insert into ev values('selected',public.create_agent_credential_v1('Existing selected',array['classes:read','class-details:read','class-info:write'],array[pg_temp.cid(20)],now()+interval '1 day'));
insert into ev values('read',public.create_agent_credential_v2('Calendar reader',array['calendar:read'],'{}',now()+interval '1 day',false));
select throws_ok($q$select public.create_agent_credential_v2('Unknown class',array['classes:read'],array[pg_temp.cid(999)],now()+interval '1 day',false)$q$,'22023','agent_invalid','v2 rejects nonexistent selected class even when other classes exist');
select throws_ok($q$select public.create_agent_credential_v1('Unknown class',array['classes:read'],array[pg_temp.cid(999)],now()+interval '1 day')$q$,'22023','agent_invalid','legacy issuer also rejects nonexistent selected class');
select is((select v#>>'{classAccess,mode}' from ev where k='all'),'all','explicit all-class mode issued');
select throws_ok($q$select public.create_agent_credential_v2('ambiguous',array['classes:read','class-details:read'],'{}',now()+interval '1 day',false)$q$,'22023','agent_invalid','empty selected class grant is rejected');
select throws_ok($q$select public.create_agent_credential_v2('invalid',array['calendar:write'],'{}',now()+interval '1 day',true)$q$,'22023','agent_invalid','calendar write requires read');
select throws_ok($q$select * from dashboard_private.agent_calendar_sources$q$,'42501',null,'source table private');
select throws_ok($q$select public.agent_calendar_api_v1(repeat('a',64),'schools')$q$,'42501',null,'calendar gateway service-only');
reset role;
insert into public.classes(id,name,class_type,subject,status,schedule_storage_mode,student_ids,teacher,room,schedule) values(pg_temp.cid(21),'Future class','regular','영어','수강','legacy','[]','Calendar test teacher','Calendar test room','화 10:00-11:00');
create function pg_temp.api(a text,i jsonb default '{}',label text default 'all') returns jsonb language sql as $$select public.agent_calendar_api_v1(encode(sha256(convert_to((select v->>'token' from ev where k=label),'UTF8')),'hex'),a,i)$$;
create function pg_temp.classes(a text,i jsonb default '{}',label text default 'all') returns jsonb language sql as $$select public.agent_api_v2(encode(sha256(convert_to((select v->>'token' from ev where k=label),'UTF8')),'hex'),a,i)$$;
create function pg_temp.command() returns jsonb language sql as $$select jsonb_build_object('schoolId',pg_temp.cid(1),'schoolYear',2099,'reason','Synthetic official update','diff','{}'::jsonb,'events',jsonb_build_array(
 jsonb_build_object('id',pg_temp.cid(2),'insert',false,'patch',jsonb_build_object('title','Midterm updated','date','2099-10-02','type','시험기간','grade','고1','note','KEEP_NOTE'),'source',jsonb_build_object('url','https://school.example/calendar','title','Official calendar','authority','official_school','checkedAt',clock_timestamp(),'schoolIdentityEvidence','Synthetic school identity')),
 jsonb_build_object('id',pg_temp.cid(3),'insert',true,'patch',jsonb_build_object('title','Vacation','date','2100-02-20','type','방학·휴일·기타','grade','all','note',null),'source',jsonb_build_object('url','https://school.example/calendar','title','Official calendar','authority','official_school','checkedAt',clock_timestamp(),'schoolIdentityEvidence','Synthetic school identity'))))$$;
create function pg_temp.preview_input(cmd jsonb default pg_temp.command()) returns jsonb language sql as $$select jsonb_build_object('schoolId',pg_temp.cid(1),'schoolYear',2099,'expectedVersion',pg_temp.api('context',jsonb_build_object('schoolId',pg_temp.cid(1),'schoolYear',2099))#>>'{data,version}','command',cmd)$$;
create function pg_temp.commit_input(label text,k int) returns jsonb language sql as $$select jsonb_build_object('previewToken',(select v#>>'{data,previewToken}' from ev where ev.k=label),'requestKey',pg_temp.cid(k),'sourceReference','synthetic')$$;
set local role service_role;
select is(pg_temp.classes('health')#>>'{data,classAccess,mode}','all','health explicitly indicates all classes');
select is(pg_temp.classes('context',jsonb_build_object('classId',pg_temp.cid(21)))#>>'{data,id}',pg_temp.cid(21)::text,'all-class key reaches a later-created class');
select throws_ok($q$select pg_temp.classes('context',jsonb_build_object('classId',pg_temp.cid(21)),'selected')$q$,'42501','agent_scope_forbidden','old selected key is never expanded');
insert into ev values('class_preview',pg_temp.classes('preview',jsonb_build_object('classId',pg_temp.cid(21),'expectedVersion',pg_temp.classes('context',jsonb_build_object('classId',pg_temp.cid(21)))#>>'{data,version}','command',jsonb_build_object('patch',jsonb_build_object('capacity',15),'reason','All-class write','window',jsonb_build_object('from','2099-10-01','to','2099-10-31')))));
select is(pg_temp.classes('commit',pg_temp.commit_input('class_preview',101))#>>'{data,state}','applied','all-class key can commit later-created class edit');
select ok(jsonb_array_length(pg_temp.api('schools')->'data'->'items')>=2,'school lookup returns stable identities');
select throws_ok($q$select pg_temp.api('context',jsonb_build_object('schoolId',pg_temp.cid(1),'schoolYear',1999))$q$,'22023','agent_invalid_range','school year bounded');
select throws_ok($q$select pg_temp.api('preview',pg_temp.preview_input(),'read')$q$,'42501','agent_scope_forbidden','calendar read cannot write');
select throws_ok($q$select pg_temp.api('schools','{}','selected')$q$,'42501','agent_scope_forbidden','class grant is not calendar grant');
insert into ev values('preview',pg_temp.api('preview',pg_temp.preview_input()));
reset role;
select is((select title from public.academic_events where id=pg_temp.cid(2)),'Midterm','preview rolls back update');
select is((select count(*) from public.academic_events where id=pg_temp.cid(3)),0::bigint,'preview rolls back insert');
select is((select count(*) from dashboard_private.agent_calendar_sources where school_id=pg_temp.cid(1)),0::bigint,'preview rolls back provenance');
set local role service_role;
insert into ev values('saved',pg_temp.api('commit',pg_temp.commit_input('preview',102)));
select is((select v#>>'{data,state}' from ev where k='saved'),'applied','calendar batch applied');
select is(pg_temp.api('commit',pg_temp.commit_input('preview',102))#>>'{data,replayed}','true','same-key commit is replayed');
select throws_ok($q$select pg_temp.api('commit',pg_temp.commit_input('preview',102)||'{"sourceReference":"different"}')$q$,'22023','agent_idempotency_key_reused','same key cannot mean different intent');
select is(pg_temp.api('operation',jsonb_build_object('requestKey',pg_temp.cid(102)))#>>'{data,state}','applied','receipt independently recoverable');
select is(pg_temp.api('operation',jsonb_build_object('requestKey',pg_temp.cid(999)))#>>'{data,retryWithNewKey}','false','unknown never licenses new-key retry');
reset role;
select is((select date::text from public.academic_events where id=pg_temp.cid(2)),'2099-10-02','updated event persists');
select is((select content from public.academic_events where id=pg_temp.cid(2)),'KEEP_CONTENT','unrequested content preserved');
select is((select note from public.academic_events where id=pg_temp.cid(5)),'KEEP_UNMENTIONED','omitted event preserved');
select is((select count(*) from dashboard_private.agent_calendar_operations where credential_id=(select (v->>'id')::uuid from ev where k='all')),1::bigint,'replay does not add operations');
select is((select count(*) from dashboard_private.agent_calendar_sources where school_id=pg_temp.cid(1)),2::bigint,'source evidence persists');
set local role service_role;
-- The second invalid target must roll back the first tentative update.
select throws_ok($q$select pg_temp.api('preview',pg_temp.preview_input(jsonb_set(jsonb_set(pg_temp.command(),'{events,1,insert}','false'),'{events,1,id}',to_jsonb(pg_temp.cid(999)::text))))$q$,'P0002','agent_not_found','invalid later item rolls back whole preview batch');
reset role;
select is((select title from public.academic_events where id=pg_temp.cid(2)),'Midterm updated','failed batch preserves first item');
set local role service_role;
insert into ev values('stale',pg_temp.api('preview',pg_temp.preview_input(jsonb_set(pg_temp.command(),'{events}',jsonb_build_array(pg_temp.command()#>'{events,0}')))));
reset role;
update public.academic_events set title='Intervening UI edit' where id=pg_temp.cid(2);
set local role service_role;
insert into ev values('stale_saved',pg_temp.api('commit',pg_temp.commit_input('stale',103)));
select is((select v#>>'{data,error,code}' from ev where k='stale_saved'),'agent_stale','concurrent UI edit rejects commit');
select is((select v#>>'{data,error,sqlstate}' from ev where k='stale_saved'),'P0001','business staleness exact SQLSTATE is P0001');
select is(pg_temp.api('operation',jsonb_build_object('requestKey',pg_temp.cid(103)))#>>'{data,state}','failed','stale failure is durable');
select is((select e->'source' from jsonb_array_elements(pg_temp.api('context',jsonb_build_object('schoolId',pg_temp.cid(1),'schoolYear',2099))#>'{data,events}') e where e->>'id'=pg_temp.cid(2)::text),'null'::jsonb,'intervening UI edit invalidates the old source claim');
insert into ev values('expires',pg_temp.api('preview',pg_temp.preview_input(jsonb_set(pg_temp.command(),'{events}',jsonb_build_array(pg_temp.command()#>'{events,0}')))));
reset role;
update dashboard_private.agent_calendar_previews set expires_at=clock_timestamp()-interval '1 second' where id=(select (v#>>'{data,previewToken}')::uuid from ev where k='expires');
set local role service_role;
insert into ev values('expired_saved',pg_temp.api('commit',pg_temp.commit_input('expires',104)));
select is((select v#>>'{data,error,code}' from ev where k='expired_saved'),'agent_preview_expired','expired preview records failure');
select is((select v#>>'{data,error,sqlstate}' from ev where k='expired_saved'),'P0001','expiry SQLSTATE is P0001');
reset role;
update public.profiles set role='teacher' where id=pg_temp.cid(10);
set local role service_role;
select throws_ok($q$select pg_temp.api('schools')$q$,'42501','agent_forbidden','issuer role loss disables calendar access');
reset role;
update public.profiles set role='admin' where id=pg_temp.cid(10);
select is((select title from public.academic_events where id=pg_temp.cid(2)),'Intervening UI edit','stale commit does not overwrite');
select is((select count(*) from dashboard_private.notification_events),(select events from no_send),'no notifications');
select is((select count(*) from dashboard_private.notification_deliveries),(select deliveries from no_send),'no deliveries');
select is((select count(*) from public.student_class_enrollment_history),(select enrollments from no_send),'no enrollment history effects');
select is((select count(*) from public.makeup_request_events),(select approvals from no_send),'no approval effects');
select set_config('request.jwt.claim.sub',pg_temp.cid(10)::text,true);
set local role authenticated;
select public.revoke_agent_credential_v1((select (v->>'id')::uuid from ev where k='all'));
set local role service_role;
select throws_ok($q$select pg_temp.api('schools')$q$,'28000','agent_unauthorized','revocation blocks new calendar access');
reset role;
select * from finish();
rollback;
