begin;
select no_plan();
create function pg_temp.aid(n int) returns uuid language sql immutable as $$select ('aa290000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
insert into auth.users(id,instance_id,aud,role,email) values
(pg_temp.aid(1),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','agent-admin@test.invalid'),
(pg_temp.aid(2),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','agent-teacher@test.invalid');
insert into public.profiles(id,role,name) values(pg_temp.aid(1),'admin','agent fixture'),(pg_temp.aid(2),'teacher','teacher fixture') on conflict(id) do update set role=excluded.role;
insert into public.teacher_catalogs(id,name,subjects) values(pg_temp.aid(101),'Agent T',array['영어']);
insert into public.classroom_catalogs(id,name,subjects) values(pg_temp.aid(201),'Agent R',array['영어']);
insert into public.classes(id,name,subject,status,schedule_storage_mode,teacher,room,schedule,schedule_plan,student_ids) values
(pg_temp.aid(301),'Agent A','영어','수강','legacy','Agent T','Agent R','월 09:00-10:00','{"sessions":[],"privateNote":"retained"}','["never-expose-student"]'),
(pg_temp.aid(302),'Agent B','영어','수강','legacy','Agent T','Agent R','월 11:00-12:00','{}','[]'),
(pg_temp.aid(303),'Agent normalized','영어','수강','normalized','Agent T','Agent R','화 09:00-10:00','{}','[]');
insert into dashboard_private.continuous_class_schedule_runtime(singleton,version) values(true,1) on conflict(singleton) do update set version=1;
select set_config('app.class_schedule_mutation','release2-rpc',true);
insert into public.class_schedule_slots(id,class_id,weekday,start_time,end_time,teacher_catalog_id,teacher_name,classroom_catalog_id,classroom_name,sort_order) values(pg_temp.aid(401),pg_temp.aid(303),2,'09:00','10:00',pg_temp.aid(101),'Agent T',pg_temp.aid(201),'Agent R',7);
set constraints all immediate;set constraints all deferred;
create temp table ev(k text primary key,v jsonb);
grant all on ev to authenticated,service_role;
create temp table no_send as select (select count(*) from dashboard_private.notification_events) events,(select count(*) from dashboard_private.notification_deliveries) deliveries,(select count(*) from public.student_class_enrollment_history) enrollments;
create temp table baseline as select schedule_plan,student_ids from public.classes where id=pg_temp.aid(301);
select set_config('request.jwt.claim.sub',pg_temp.aid(2)::text,true);
set local role authenticated;
select throws_ok($q$select public.create_agent_credential_v1('teacher',array['classes:read'],'{}',now()+interval '1 day')$q$,'42501','agent_forbidden','teacher cannot mint agent authority');
reset role;
select set_config('request.jwt.claim.sub',pg_temp.aid(1)::text,true);
set local role authenticated;
select throws_ok($q$select public.create_agent_credential_v1('broad',array['classes:read','schedule:preview','schedule:write'],'{}',now()+interval '1 day')$q$,'22023','agent_invalid','write capability requires explicit class IDs');
insert into ev values('read',public.create_agent_credential_v1('Muse read',array['classes:read'],array[pg_temp.aid(301)],now()+interval '1 day'));
insert into ev values('write',public.create_agent_credential_v1('Muse fixture',array['classes:read','calendar:read','schedule:preview','schedule:write'],array[pg_temp.aid(301),pg_temp.aid(303)],now()+interval '1 day'));
insert into ev values('other',public.create_agent_credential_v1('Other',array['classes:read','schedule:preview','schedule:write'],array[pg_temp.aid(301)],now()+interval '1 day'));
select is(public.list_agent_credentials_v1(1,10)->>'total','3','issuer-only paginated credential count');
select throws_ok($q$select public.list_agent_credentials_v1(0,10)$q$,'22023','agent_invalid','invalid listing page denied');
select ok(not (public.list_agent_credentials_v1()::text like '%tips_agent_%'),'credential list never returns secret');
select throws_ok($q$select * from dashboard_private.agent_credentials$q$,'42501',null,'authenticated cannot read token hashes');
select throws_ok($q$select public.agent_api_v1(repeat('a',64),'health')$q$,'42501',null,'ordinary authenticated role cannot call service gateway');
reset role;
create function pg_temp.api(a text,i jsonb default '{}',label text default 'write') returns jsonb language sql as $$select public.agent_api_v1(encode(sha256(convert_to((select v->>'token' from ev where k=label),'UTF8')),'hex'),a,i)$$;
create function pg_temp.input(cid int,a int,b int) returns jsonb language sql as $$select jsonb_build_object('classId',pg_temp.aid(cid),'expectedVersion',v#>>'{data,version}','slotId',v#>>'{data,weeklySlots,0,id}','startMinute',a,'endMinute',b,'reason','synthetic test') from (select pg_temp.api('class',jsonb_build_object('classId',pg_temp.aid(cid))) v) t$$;
set local role service_role;
select throws_ok($q$select public.agent_api_v1(repeat('a',64),'health')$q$,'28000','agent_unauthorized','unknown key denied');
select is(pg_temp.api('classes','{}','read')#>>'{data,total}','1','class grant limits search results');
select ok(not (pg_temp.api('class',jsonb_build_object('classId',pg_temp.aid(301)))::text like '%never-expose%'),'no student identities returned');
select ok(not (pg_temp.api('class',jsonb_build_object('classId',pg_temp.aid(301)))::text like '%privateNote%'),'no private notes returned');
select throws_ok($q$select pg_temp.api('class',jsonb_build_object('classId',pg_temp.aid(302)),'read')$q$,'P0002','agent_not_found','out-of-grant class cannot be read');
select throws_ok($q$select pg_temp.api('preview',pg_temp.input(301,600,660),'read')$q$,'42501','agent_scope_forbidden','read key cannot preview writes');
select throws_ok($q$select pg_temp.api('preview',pg_temp.input(301,660,720))$q$,'23P01','timetable_resource_conflict','preview uses exact SQLSTATE from final timetable guard');
insert into ev values('preview',pg_temp.api('preview',pg_temp.input(301,600,660)));
reset role;
select is((select schedule from public.classes where id=pg_temp.aid(301)),'월 09:00-10:00','preview rolled back business writes');
select is((select count(*) from dashboard_private.class_schedule_mutation_receipts where actor_profile_id=pg_temp.aid(1)),0::bigint,'preview rolled back domain receipts');
select is((select count(*) from dashboard_private.agent_operations),0::bigint,'preview is not a completed operation');
set local role service_role;
select throws_ok($q$select pg_temp.api('commit',jsonb_build_object('previewToken',(select v#>>'{data,previewToken}' from ev where k='preview'),'requestKey',pg_temp.aid(501)),'other')$q$,'P0002','agent_not_found','preview is bound to exact credential');
insert into ev values('saved',pg_temp.api('commit',jsonb_build_object('previewToken',(select v#>>'{data,previewToken}' from ev where k='preview'),'requestKey',pg_temp.aid(501))));
select is((select v#>>'{data,state}' from ev where k='saved'),'applied','authorized commit applied');
select is(pg_temp.api('operation',jsonb_build_object('requestKey',pg_temp.aid(501)))#>>'{data,state}','applied','lost-response lookup recovers durable receipt');
select is(pg_temp.api('operation',jsonb_build_object('requestKey',pg_temp.aid(501)),'other')#>>'{data,state}','unknown','operation lookup is credential scoped');
select is(pg_temp.api('commit',jsonb_build_object('previewToken',(select v#>>'{data,previewToken}' from ev where k='preview'),'requestKey',pg_temp.aid(501)))#>>'{data,replayed}','true','same operation key replays original outcome');
select throws_ok($q$select pg_temp.api('commit',jsonb_build_object('previewToken',(select v#>>'{data,previewToken}' from ev where k='preview'),'requestKey',pg_temp.aid(502)))$q$,'22023','agent_preview_consumed','new request key cannot execute same preview twice');
select throws_ok($q$select pg_temp.api('commit',jsonb_build_object('previewToken',pg_temp.aid(999),'requestKey',pg_temp.aid(501)))$q$,'22023','agent_idempotency_key_reused','same request key cannot change payload');
reset role;
select is((select count(*) from dashboard_private.agent_operations),1::bigint,'only one durable mutation');
select is((select schedule_plan from public.classes where id=pg_temp.aid(301)),(select schedule_plan from baseline),'learning and historical plan preserved');
select is((select student_ids from public.classes where id=pg_temp.aid(301)),(select student_ids from baseline),'students preserved');
select is((select v#>>'{data,requesterVerified}' from ev where k='saved'),'false','unverified chat requester never becomes authenticated actor');
select is((select v#>>'{data,notifications,state}' from ev where k='saved'),'not_requested','no implied send success');
set local role service_role;
insert into ev values('stale',pg_temp.api('preview',pg_temp.input(301,540,600)));
reset role;
update public.classes set schedule='월 13:00-14:00 (Agent T, Agent R)' where id=pg_temp.aid(301);
set constraints all immediate;set constraints all deferred;
set local role service_role;
select is(pg_temp.api('commit',jsonb_build_object('previewToken',(select v#>>'{data,previewToken}' from ev where k='stale'),'requestKey',pg_temp.aid(503)))#>>'{data,error,code}','agent_stale','stale preview becomes durable failure');
select is(pg_temp.api('operation',jsonb_build_object('requestKey',pg_temp.aid(503)))#>>'{data,state}','failed','failed outcome is recoverable');
insert into ev values('normalized',pg_temp.api('preview',pg_temp.input(303,600,660)));
select is(pg_temp.api('commit',jsonb_build_object('previewToken',(select v#>>'{data,previewToken}' from ev where k='normalized'),'requestKey',pg_temp.aid(504)))#>>'{data,state}','applied','normalized writer supported too');
reset role;
select is((select start_time::text from public.class_schedule_slots where id=pg_temp.aid(401)),'10:00:00','normalized time persisted');
select is((select sort_order from public.class_schedule_slots where id=pg_temp.aid(401)),7,'unrelated sort order preserved');
-- A new conflict between preview and commit must be checked again.
set local role service_role;
insert into ev values('race',pg_temp.api('preview',pg_temp.input(301,840,900)));
reset role;
update public.classes set schedule='월 14:00-15:00' where id=pg_temp.aid(302);
set constraints all immediate;set constraints all deferred;
set local role service_role;
select is(pg_temp.api('commit',jsonb_build_object('previewToken',(select v#>>'{data,previewToken}' from ev where k='race'),'requestKey',pg_temp.aid(505)))#>>'{data,error,sqlstate}','23P01','commit rechecks concurrent resource change with exact SQLSTATE');
reset role;
select is((select schedule from public.classes where id=pg_temp.aid(301)),'월 13:00-14:00 (Agent T, Agent R)','conflicted commit rolled back fully');
-- Expiry, suspension, and rate limits are checked by the final gateway.
update auth.users set banned_until=now()+interval '1 day' where id=pg_temp.aid(1);
set local role service_role;
select throws_ok($q$select pg_temp.api('health')$q$,'42501','agent_forbidden','banned issuer loses authority');
reset role;
update auth.users set banned_until=null,deleted_at=now() where id=pg_temp.aid(1);
set local role service_role;
select throws_ok($q$select pg_temp.api('health')$q$,'42501','agent_forbidden','soft deleted issuer loses authority');
reset role;
update auth.users set deleted_at=null where id=pg_temp.aid(1);
update dashboard_private.agent_credentials set expires_at=now()-interval '1 second' where id=(select (v->>'id')::uuid from ev where k='read');
set local role service_role;
select throws_ok($q$select pg_temp.api('health','{}','read')$q$,'28000','agent_unauthorized','expired token rejected');
reset role;
update dashboard_private.agent_credentials set rate_window=date_trunc('minute',clock_timestamp()),rate_count=60 where id=(select (v->>'id')::uuid from ev where k='other');
set local role service_role;
select is(pg_temp.api('health','{}','other')#>>'{error,code}','agent_rate_limited','per-token limit returns typed retryable result');
reset role;
update public.profiles set role='viewer' where id=pg_temp.aid(1);
set local role service_role;
select throws_ok($q$select pg_temp.api('health')$q$,'42501','agent_forbidden','issuer downgrade revokes effective authority immediately');
reset role;
update public.profiles set role='admin' where id=pg_temp.aid(1);
select set_config('request.jwt.claim.sub',pg_temp.aid(1)::text,true);
set local role authenticated;
select public.revoke_agent_credential_v1((select (v->>'id')::uuid from ev where k='write'));
reset role;
set local role service_role;
select throws_ok($q$select pg_temp.api('health')$q$,'28000','agent_unauthorized','revoked key cannot be used');
reset role;
-- Integration audit data must not block existing class/account deletion.
insert into public.classes(id,name,subject,status,schedule_storage_mode,teacher,room,schedule,schedule_plan,student_ids)
values(pg_temp.aid(304),'Disposable synthetic class','영어','수강','legacy','Agent T','Agent R','수 09:00-10:00','{}','[]');
select set_config('request.jwt.claim.sub',pg_temp.aid(1)::text,true);
set local role authenticated;
insert into ev values('lifecycle',public.create_agent_credential_v1('lifecycle',array['classes:read','schedule:preview','schedule:write'],array[pg_temp.aid(304)],now()+interval '1 day'));
reset role;
set local role service_role;
insert into ev values('removed-class-preview',pg_temp.api('preview',jsonb_build_object('classId',pg_temp.aid(304),'expectedVersion',pg_temp.api('class',jsonb_build_object('classId',pg_temp.aid(304)),'lifecycle')#>>'{data,version}','slotId',pg_temp.api('class',jsonb_build_object('classId',pg_temp.aid(304)),'lifecycle')#>>'{data,weeklySlots,0,id}','startMinute',600,'endMinute',660,'reason','synthetic lifecycle'),'lifecycle'));
reset role;
select lives_ok($q$delete from public.classes where id=pg_temp.aid(304)$q$,'preview history does not prevent an existing class deletion');
set local role service_role;
select is(pg_temp.api('commit',jsonb_build_object('previewToken',(select v#>>'{data,previewToken}' from ev where k='removed-class-preview'),'requestKey',pg_temp.aid(506)),'lifecycle')#>>'{data,state}','failed','deleted target is rejected and failure receipt persists');
reset role;
insert into auth.users(id,instance_id,aud,role,email) values(pg_temp.aid(3),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','agent-disposable@test.invalid');
insert into public.profiles(id,role,name) values(pg_temp.aid(3),'admin','disposable issuer') on conflict(id) do update set role='admin';
select set_config('request.jwt.claim.sub',pg_temp.aid(3)::text,true);
set local role authenticated;
insert into ev values('orphan',public.create_agent_credential_v1('disposable',array['classes:read'],array[pg_temp.aid(301)],now()+interval '1 day'));
reset role;
select lives_ok($q$delete from public.profiles where id=pg_temp.aid(3)$q$,'key history does not prevent profile deletion');
select lives_ok($q$delete from auth.users where id=pg_temp.aid(3)$q$,'key history does not prevent account deletion');
set local role service_role;
select throws_ok($q$select pg_temp.api('health','{}','orphan')$q$,'42501','agent_forbidden','deleted issuer cannot use the retained key record');
reset role;
set constraints all immediate;
select is((select count(*) from dashboard_private.notification_events),(select events from no_send),'no notification events');
select is((select count(*) from dashboard_private.notification_deliveries),(select deliveries from no_send),'no external deliveries');
select is((select count(*) from public.student_class_enrollment_history),(select enrollments from no_send),'enrollment history preserved');
select ok(not has_function_privilege('anon','public.agent_api_v1(text,text,jsonb)','execute'),'anonymous cannot invoke gateway');
select ok(not has_function_privilege('authenticated','dashboard_private.agent_apply_weekly_time_v1(uuid,jsonb,uuid)','execute'),'private writer remains private');
select * from finish();rollback;
