begin;
select no_plan();
create function pg_temp.t8(n int) returns uuid language sql immutable as $$select ('a8230000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
insert into auth.users(id,instance_id,aud,role,email) values(pg_temp.t8(1),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','task8-errors@test.invalid');
insert into public.profiles(id,role,name) values(pg_temp.t8(1),'admin','Task8 errors') on conflict(id) do update set role='admin';
delete from public.teacher_catalogs where profile_id=pg_temp.t8(1);
insert into public.teacher_catalogs(id,name,subjects,profile_id) values(pg_temp.t8(2),'Task8 error teacher',array['영어'],pg_temp.t8(1));
insert into public.classroom_catalogs(id,name,subjects) values(pg_temp.t8(3),'Task8 error room',array['영어']);
insert into public.classes(id,name,subject,teacher,room,status,schedule_storage_mode,schedule_plan) values(pg_temp.t8(4),'Task8 errors','영어','Task8 error teacher','Task8 error room','개강 준비','normalized','{}');
select set_config('app.class_schedule_mutation','release2-rpc',true);
insert into public.class_lesson_sessions(id,class_id,session_key,session_date,schedule_state,start_time,end_time,teacher_catalog_id,classroom_catalog_id,origin) values(pg_temp.t8(5),pg_temp.t8(4),'original','2026-11-04','active','07:00','07:30',pg_temp.t8(2),pg_temp.t8(3),'manual'),(pg_temp.t8(6),pg_temp.t8(4),'makeup-existing','2026-11-05','active','07:00','07:30',pg_temp.t8(2),pg_temp.t8(3),'manual');
insert into public.makeup_requests(id,status,request_kind,subject,approval_group,requester_id,class_id,class_name,teacher_catalog_id,teacher_profile_id,approver_teacher_catalog_id,approver_profile_id,original_lesson_session_id,original_lesson_session_revision,makeup_effect_revision,makeup_slots)
values(pg_temp.t8(7),'approval_pending','makeup_only','영어','english',pg_temp.t8(1),pg_temp.t8(4),'Task8 errors',pg_temp.t8(2),pg_temp.t8(1),pg_temp.t8(2),pg_temp.t8(1),pg_temp.t8(5),0,0,'[{"startAt":"2026-11-06T07:00:00+09:00","endAt":"2026-11-06T07:30:00+09:00","classroom":"Task8 error room"}]');
set constraints all immediate;set constraints all deferred;
select set_config('app.class_schedule_mutation','',true);
select set_config('request.jwt.claim.sub',pg_temp.t8(1)::text,true);
select set_config('request.jwt.claim.role','service_role',true);
create function pg_temp.patch() returns jsonb language sql as $$select jsonb_build_object('actor_profile_id',pg_temp.t8(1),'final_note','Task8 approval audit','schedule_plan_before','{}'::jsonb,'schedule_plan_after','{}'::jsonb,'makeup_academic_event_ids','[]'::jsonb,'calendar_events','[]'::jsonb)$$;
select throws_ok($$select public.transition_makeup_request_v2(pg_temp.t8(7),'approve',pg_temp.patch(),'completed',pg_temp.t8(80))$$,'P0001','makeup_request_stale_status','public final transition stale status');
savepoint source_missing;
update public.makeup_requests set class_id=null where id=pg_temp.t8(7);
select throws_ok($$select public.transition_makeup_request_v2(pg_temp.t8(7),'approve',pg_temp.patch(),'approval_pending',pg_temp.t8(81))$$,'P0001','makeup_request_source_changed','missing source branch');
rollback to source_missing;
update public.makeup_requests set class_name='changed' where id=pg_temp.t8(7);
select throws_ok($$select public.transition_makeup_request_v2(pg_temp.t8(7),'approve',pg_temp.patch(),'approval_pending',pg_temp.t8(82))$$,'P0001','makeup_request_source_changed','changed source branch');
update public.makeup_requests set class_name='Task8 errors' where id=pg_temp.t8(7);
select throws_ok($$select dashboard_private.notification_revert_makeup_calendar_effects_legacy_v1(pg_temp.t8(7),pg_temp.t8(4),'{"wrong":1}','{"wrong":2}',null,null,'[]')$$,'P0001','makeup_schedule_plan_stale','legacy revert stale');
create function pg_temp.legacy(before_plan jsonb) returns void language plpgsql as $$begin perform dashboard_private.notification_apply_makeup_calendar_effects_legacy_v1(pg_temp.t8(7),pg_temp.t8(4),before_plan,'{}',pg_temp.t8(9),null,'[]',jsonb_build_array(jsonb_build_object('id',pg_temp.t8(9),'title','fixture','date','2026-11-06','type','팁스','grade','all','note','[[TIPS_MAKEUP]]'||pg_temp.t8(7)::text)));end$$;
select throws_ok($$select pg_temp.legacy('{"wrong":1}')$$,'P0001','makeup_schedule_plan_stale','legacy apply stale');
insert into public.academic_events(id,title,date,type,grade,note) values(pg_temp.t8(9),'different owner','2026-11-06','팁스','all','not our makeup');
select throws_ok($$select pg_temp.legacy('{}')$$,'23P01','makeup_calendar_event_conflict','legacy event ownership collision');
update public.makeup_requests set original_lesson_session_id=null where id=pg_temp.t8(7);
select throws_ok($$select dashboard_private.apply_normalized_makeup_effect_v1(pg_temp.t8(7),pg_temp.t8(4),'[]')$$,'P0001','makeup_lesson_session_stale','normalized apply missing session');
select throws_ok($$select dashboard_private.revert_normalized_makeup_effect_v1(pg_temp.t8(7),pg_temp.t8(4))$$,'P0001','makeup_lesson_session_stale','normalized revert missing session');
update public.makeup_requests set original_lesson_session_id=pg_temp.t8(5),original_lesson_session_revision=999 where id=pg_temp.t8(7);
select throws_ok($$select dashboard_private.apply_normalized_makeup_effect_v1(pg_temp.t8(7),pg_temp.t8(4),'[]')$$,'P0001','makeup_lesson_session_stale','normalized apply revision branch');
select set_config('app.class_schedule_mutation','release2-rpc',true);
update public.class_lesson_sessions set revision=1 where id=pg_temp.t8(6);
select set_config('app.class_schedule_mutation','',true);
update public.makeup_requests set original_lesson_session_revision=0,makeup_lesson_session_ids=jsonb_build_array(pg_temp.t8(6)) where id=pg_temp.t8(7);
select throws_ok($$select dashboard_private.revert_normalized_makeup_effect_v1(pg_temp.t8(7),pg_temp.t8(4))$$,'P0001','makeup_lesson_session_stale','normalized revert changed created session branch');
update public.makeup_requests set makeup_lesson_session_ids='[]' where id=pg_temp.t8(7);
insert into public.makeup_requests(id,status,request_kind,subject,approval_group,class_name,makeup_slots) select pg_temp.t8(8),'completed','makeup_only','영어','english','other',makeup_slots from public.makeup_requests where id=pg_temp.t8(7);
select throws_ok($$select dashboard_private.notification_assert_makeup_room_available_v1(pg_temp.t8(7))$$,'23P01','makeup_room_collision','final room assertion collision');
delete from public.makeup_requests where id=pg_temp.t8(8);
-- Preserve preexisting values for all five settings on success and rollback.
select set_config('app.class_schedule_class_id','prior-class',true);
select set_config('app.class_schedule_request_key','prior-request',true);
select set_config('app.class_schedule_request_operation','prior-operation',true);
select set_config('app.class_schedule_change_reason','prior-reason',true);
create function pg_temp.context_snapshot() returns jsonb language sql as $$select jsonb_object_agg(k,current_setting(k,true)) from unnest(array['app.class_schedule_mutation','app.class_schedule_class_id','app.class_schedule_request_key','app.class_schedule_request_operation','app.class_schedule_change_reason']) k$$;
create temp table context_before as select pg_temp.context_snapshot() value;
update public.makeup_requests set makeup_slots='[{"startAt":"2026-11-06T07:00:00+09:00","endAt":"2026-11-07T08:00:00+09:00","classroom":"Task8 error room"}]' where id=pg_temp.t8(7);
select throws_ok($$select public.transition_makeup_request_v2(pg_temp.t8(7),'approve',pg_temp.patch(),'approval_pending',pg_temp.t8(85))$$,'22023','class_schedule_validation','public failure after context and first session update rolls back');
select is(pg_temp.context_snapshot(),(select value from context_before),'all five context settings restored after statement failure');
select is((select schedule_state from public.class_lesson_sessions where id=pg_temp.t8(5)),'active','failed public effect leaves original session untouched');
select throws_ok($$update public.class_lesson_sessions set memo='unauthorized' where id=pg_temp.t8(5)$$,'42501','continuous class schedule direct write is not allowed','failed effect leaves direct writes denied');
update public.makeup_requests set makeup_slots='[{"startAt":"2026-11-06T07:00:00+09:00","endAt":"2026-11-06T07:30:00+09:00","classroom":"Task8 error room"}]' where id=pg_temp.t8(7);

-- A fresh public approval must establish its own trusted context, then restore it.
select lives_ok($$select public.transition_makeup_request_v2(pg_temp.t8(7),'approve',pg_temp.patch(),'approval_pending',pg_temp.t8(83))$$,'public normalized approval without fixture GUC');
select is(pg_temp.context_snapshot(),(select value from context_before),'approval restores all five caller context values');
select is((select status from public.makeup_requests where id=pg_temp.t8(7)),'completed','actual public approval committed effect');
select throws_ok($$update public.class_lesson_sessions set memo='unauthorized' where id=pg_temp.t8(5)$$,'42501','continuous class schedule direct write is not allowed','no direct-write permission leak after public effect');
select ok(exists(select 1 from public.dashboard_audit_logs where entity_table='class_lesson_sessions' and class_id=pg_temp.t8(4) and request_key=pg_temp.t8(83) and request_operation='makeup_approve' and change_reason='Task8 approval audit'),'public approval audit uses actual mutation key, operation and reason');
select lives_ok($$select public.transition_makeup_request_v2(pg_temp.t8(7),'approval_canceled','{"note":"Task8 cancel audit"}','completed',pg_temp.t8(84))$$,'public normalized cancellation establishes and restores context');
select is(pg_temp.context_snapshot(),(select value from context_before),'revert restores all five caller context values');
select throws_ok($$update public.class_lesson_sessions set memo='unauthorized' where id=pg_temp.t8(5)$$,'42501','continuous class schedule direct write is not allowed','revert leaves direct writes denied');
select is((select schedule_state from public.class_lesson_sessions where id=pg_temp.t8(5)),'active','revert preserves original session identity');
select ok(exists(select 1 from public.dashboard_audit_logs where entity_table='class_lesson_sessions' and class_id=pg_temp.t8(4) and request_key=pg_temp.t8(84) and request_operation='makeup_approval_canceled' and change_reason='Task8 cancel audit'),'public cancel audit uses actual mutation key, operation and reason');
select * from finish();
rollback;
