begin;
do $$begin
 if not exists(select 1 from pg_catalog.pg_extension where extname='pgtap') then
  create extension pgtap with schema extensions;
 end if;
end $$;
select no_plan();
create function pg_temp.tid(n int) returns uuid language sql immutable as $$select ('ac239000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
insert into auth.users(id,instance_id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select pg_temp.tid(n),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','plan'||n||'@test.invalid','{}','{}',now(),now() from generate_series(901,905) n;
insert into public.profiles(id,role,name,email) select pg_temp.tid(n),case n when 901 then 'admin' when 902 then 'staff' when 905 then 'assistant' else 'teacher' end,'plan actor '||n,'plan'||n||'@test.invalid' from generate_series(901,905) n on conflict(id) do update set role=excluded.role;
delete from public.teacher_catalogs where profile_id in(pg_temp.tid(903),pg_temp.tid(904));
insert into public.teacher_catalogs(id,name,subjects,profile_id) values(pg_temp.tid(101),'동일 이름',array['영어팀'],pg_temp.tid(903)),(pg_temp.tid(102),'다른 교사',array['영어'],pg_temp.tid(904));
update public.profiles set teacher_catalog_id=case id when pg_temp.tid(903) then pg_temp.tid(101) else pg_temp.tid(102) end where id in(pg_temp.tid(903),pg_temp.tid(904));
insert into public.classroom_catalogs(id,name,subjects) values(pg_temp.tid(201),'동일 이름',array['영어']),(pg_temp.tid(202),'다른 방',array['영어']);
create function pg_temp.cmd(i int, rev int default null, start_at int default 600, end_at int default 660, k text default 'save') returns jsonb language sql as $$select jsonb_build_object('operation','save','planId',pg_temp.tid(1),'expectedMetaRevision',0,'expectedShadowFingerprint',public.get_timetable_plan_revision_v1(pg_temp.tid(1))->>'shadowFingerprint','expectedItemRevision',rev,'requestKey',k,'item',jsonb_build_object('id',pg_temp.tid(i),'planId',pg_temp.tid(1),'name','초안','subject','영어','subjectAreaKey',null,'grade','중2','capacity',12,'tuition',100000,'defaultTeacherId',pg_temp.tid(101),'defaultClassroomId',pg_temp.tid(201),'durationMinutes',60,'pendingSlots','[]'::jsonb),'slots',jsonb_build_array(jsonb_build_object('id',pg_temp.tid(i+100),'itemId',pg_temp.tid(i),'planId',pg_temp.tid(1),'weekday',1,'startMinute',start_at,'endMinute',end_at,'teacherId',pg_temp.tid(101),'classroomId',pg_temp.tid(201),'sourceSlotId',null)))$$;
select set_config('request.jwt.claim.sub',pg_temp.tid(901)::text,true);
set local role authenticated;
select lives_ok($$select public.mutate_timetable_plan_v1(jsonb_build_object('operation','create','planId',pg_temp.tid(1),'name','원장 계획','requestKey','create'))$$,'director creates preset');
select lives_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(11))$$,'director edits preset');
select throws_ok($$insert into public.timetable_plans(name,created_by,updated_by) values('bypass',pg_temp.tid(901),pg_temp.tid(901))$$,'42501',null,'direct writes stay denied');
reset role;
insert into public.timetable_plan_members(plan_id,user_id,access) values(pg_temp.tid(1),pg_temp.tid(903),'editor'),(pg_temp.tid(1),pg_temp.tid(904),'viewer');
select set_config('request.jwt.claim.sub',pg_temp.tid(902)::text,true);
set local role authenticated;
select throws_ok($$select public.list_timetable_plans_v1()$$,'42501','timetable_forbidden','staff cannot call preset RPC');
select throws_ok($$select public.get_timetable_plan_v1(pg_temp.tid(1))$$,'42501','timetable_forbidden','staff cannot call preset RPC');
select throws_ok($$select public.get_timetable_plan_revision_v1(pg_temp.tid(1))$$,'42501','timetable_forbidden','staff cannot call preset RPC');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(11))$$,'42501','timetable_forbidden','staff cannot call preset RPC');
select throws_ok($$select public.mutate_timetable_plan_v1(jsonb_build_object('operation','create','planId',pg_temp.tid(2),'name','blocked','requestKey','blocked'))$$,'42501','timetable_forbidden','staff cannot call preset RPC');
select is((select count(*) from public.timetable_plans where id=pg_temp.tid(1)),0::bigint,'staff cannot read timetable_plans through RLS');
select is((select count(*) from public.timetable_plan_items where plan_id=pg_temp.tid(1)),0::bigint,'staff cannot read timetable_plan_items through RLS');
select is((select count(*) from public.timetable_plan_slots where plan_id=pg_temp.tid(1)),0::bigint,'staff cannot read timetable_plan_slots through RLS');
select is((select count(*) from public.timetable_plan_members where plan_id=pg_temp.tid(1)),0::bigint,'staff cannot read timetable_plan_members through RLS');
select is((select count(*) from public.timetable_invalidation_signals where plan_id=pg_temp.tid(1)),0::bigint,'staff cannot read preset signals');
select lives_ok($$select public.get_timetable_operational_reference_v1()$$,'staff can still read operating timetable');
reset role;
select set_config('request.jwt.claim.sub',pg_temp.tid(903)::text,true);
set local role authenticated;
select throws_ok($$select public.list_timetable_plans_v1()$$,'42501','timetable_forbidden','legacy editor cannot call preset RPC');
select throws_ok($$select public.get_timetable_plan_v1(pg_temp.tid(1))$$,'42501','timetable_forbidden','legacy editor cannot call preset RPC');
select throws_ok($$select public.get_timetable_plan_revision_v1(pg_temp.tid(1))$$,'42501','timetable_forbidden','legacy editor cannot call preset RPC');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(11))$$,'42501','timetable_forbidden','legacy editor cannot call preset RPC');
select throws_ok($$select public.mutate_timetable_plan_v1(jsonb_build_object('operation','create','planId',pg_temp.tid(2),'name','blocked','requestKey','blocked'))$$,'42501','timetable_forbidden','legacy editor cannot call preset RPC');
select is((select count(*) from public.timetable_plans where id=pg_temp.tid(1)),0::bigint,'legacy editor cannot read timetable_plans through RLS');
select is((select count(*) from public.timetable_plan_items where plan_id=pg_temp.tid(1)),0::bigint,'legacy editor cannot read timetable_plan_items through RLS');
select is((select count(*) from public.timetable_plan_slots where plan_id=pg_temp.tid(1)),0::bigint,'legacy editor cannot read timetable_plan_slots through RLS');
select is((select count(*) from public.timetable_plan_members where plan_id=pg_temp.tid(1)),0::bigint,'legacy editor cannot read timetable_plan_members through RLS');
select is((select count(*) from public.timetable_invalidation_signals where plan_id=pg_temp.tid(1)),0::bigint,'legacy editor cannot read preset signals');
select lives_ok($$select public.get_timetable_operational_reference_v1()$$,'legacy editor can still read operating timetable');
reset role;
select set_config('request.jwt.claim.sub',pg_temp.tid(904)::text,true);
set local role authenticated;
select throws_ok($$select public.list_timetable_plans_v1()$$,'42501','timetable_forbidden','legacy viewer cannot call preset RPC');
select throws_ok($$select public.get_timetable_plan_v1(pg_temp.tid(1))$$,'42501','timetable_forbidden','legacy viewer cannot call preset RPC');
select throws_ok($$select public.get_timetable_plan_revision_v1(pg_temp.tid(1))$$,'42501','timetable_forbidden','legacy viewer cannot call preset RPC');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(11))$$,'42501','timetable_forbidden','legacy viewer cannot call preset RPC');
select throws_ok($$select public.mutate_timetable_plan_v1(jsonb_build_object('operation','create','planId',pg_temp.tid(2),'name','blocked','requestKey','blocked'))$$,'42501','timetable_forbidden','legacy viewer cannot call preset RPC');
select is((select count(*) from public.timetable_plans where id=pg_temp.tid(1)),0::bigint,'legacy viewer cannot read timetable_plans through RLS');
select is((select count(*) from public.timetable_plan_items where plan_id=pg_temp.tid(1)),0::bigint,'legacy viewer cannot read timetable_plan_items through RLS');
select is((select count(*) from public.timetable_plan_slots where plan_id=pg_temp.tid(1)),0::bigint,'legacy viewer cannot read timetable_plan_slots through RLS');
select is((select count(*) from public.timetable_plan_members where plan_id=pg_temp.tid(1)),0::bigint,'legacy viewer cannot read timetable_plan_members through RLS');
select is((select count(*) from public.timetable_invalidation_signals where plan_id=pg_temp.tid(1)),0::bigint,'legacy viewer cannot read preset signals');
select lives_ok($$select public.get_timetable_operational_reference_v1()$$,'legacy viewer can still read operating timetable');
reset role;
select set_config('request.jwt.claim.sub',pg_temp.tid(905)::text,true);
set local role authenticated;
select throws_ok($$select public.list_timetable_plans_v1()$$,'42501','timetable_forbidden','assistant cannot call preset RPC');
select throws_ok($$select public.get_timetable_plan_v1(pg_temp.tid(1))$$,'42501','timetable_forbidden','assistant cannot call preset RPC');
select throws_ok($$select public.get_timetable_plan_revision_v1(pg_temp.tid(1))$$,'42501','timetable_forbidden','assistant cannot call preset RPC');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(11))$$,'42501','timetable_forbidden','assistant cannot call preset RPC');
select throws_ok($$select public.mutate_timetable_plan_v1(jsonb_build_object('operation','create','planId',pg_temp.tid(2),'name','blocked','requestKey','blocked'))$$,'42501','timetable_forbidden','assistant cannot call preset RPC');
select is((select count(*) from public.timetable_plans where id=pg_temp.tid(1)),0::bigint,'assistant cannot read timetable_plans through RLS');
select is((select count(*) from public.timetable_plan_items where plan_id=pg_temp.tid(1)),0::bigint,'assistant cannot read timetable_plan_items through RLS');
select is((select count(*) from public.timetable_plan_slots where plan_id=pg_temp.tid(1)),0::bigint,'assistant cannot read timetable_plan_slots through RLS');
select is((select count(*) from public.timetable_plan_members where plan_id=pg_temp.tid(1)),0::bigint,'assistant cannot read timetable_plan_members through RLS');
select is((select count(*) from public.timetable_invalidation_signals where plan_id=pg_temp.tid(1)),0::bigint,'assistant cannot read preset signals');
reset role;
select set_config('request.jwt.claim.sub',pg_temp.tid(901)::text,true);
set local role authenticated;
select lives_ok($$select public.get_timetable_plan_v1(pg_temp.tid(1))$$,'director still reads preset');
select is((public.get_timetable_plan_v1(pg_temp.tid(1))#>>'{permissions,canTransfer}')::boolean,true,'director can publish');
select throws_ok($$select dashboard_private.read_timetable_operating_reference_v1()$$,'42501',null,'private reader stays private');
select throws_ok($$select * from dashboard_private.timetable_plan_mutation_receipts$$,'42501',null,'receipts stay private');
reset role;
update public.profiles set role='teacher' where id=pg_temp.tid(901);
set local role authenticated;
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(11))$$,'42501','timetable_forbidden','demoted director cannot replay a receipt');
reset role;
select set_config('request.jwt.claim.sub','',true);
set local role anon;
select throws_ok($$select public.get_timetable_plan_v1(pg_temp.tid(1))$$,'42501',null,'anon denied');
reset role;
select * from finish();
rollback;
