begin;
do $$begin
 if not exists(select 1 from pg_catalog.pg_extension where extname='pgtap') then
  create extension pgtap with schema extensions;
 end if;
end $$;
select no_plan();
create function pg_temp.tid(n int) returns uuid language sql immutable as $$select ('ac239000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
insert into auth.users(id,instance_id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select pg_temp.tid(n),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','plan'||n||'@test.invalid','{}','{}',now(),now() from generate_series(901,905) n;
insert into public.profiles(id,role,name,email) select pg_temp.tid(n),case n when 901 then 'admin' when 902 then 'staff' when 905 then 'assistant' else 'teacher' end,'plan actor '||n,'plan'||n||'@test.invalid' from generate_series(901,905) n on conflict(id) do update set role=excluded.role;
delete from public.teacher_catalogs where profile_id in(pg_temp.tid(903),pg_temp.tid(904));
insert into public.teacher_catalogs(id,name,subjects,profile_id) values(pg_temp.tid(101),'동일 이름',array['영어팀'],pg_temp.tid(903)),(pg_temp.tid(102),'다른 교사',array['영어'],pg_temp.tid(904));
update public.profiles set teacher_catalog_id=case id when pg_temp.tid(903) then pg_temp.tid(101) else pg_temp.tid(102) end where id in(pg_temp.tid(903),pg_temp.tid(904));
insert into public.classroom_catalogs(id,name,subjects) values(pg_temp.tid(201),'동일 이름',array['영어']),(pg_temp.tid(202),'다른 방',array['영어']);
create function pg_temp.cmd(i int, rev int default null, start_at int default 600, end_at int default 660, k text default 'save') returns jsonb language sql as $$select jsonb_build_object('operation','save','planId',pg_temp.tid(1),'expectedMetaRevision',0,'expectedShadowFingerprint',public.get_timetable_plan_revision_v1(pg_temp.tid(1))->>'shadowFingerprint','expectedItemRevision',rev,'requestKey',k,'item',jsonb_build_object('id',pg_temp.tid(i),'planId',pg_temp.tid(1),'name','초안','subject','영어','subjectAreaKey',null,'grade','중2','capacity',12,'tuition',100000,'defaultTeacherId',pg_temp.tid(101),'defaultClassroomId',pg_temp.tid(201),'durationMinutes',60,'pendingSlots','[]'::jsonb),'slots',jsonb_build_array(jsonb_build_object('id',pg_temp.tid(i+100),'itemId',pg_temp.tid(i),'planId',pg_temp.tid(1),'weekday',1,'startMinute',start_at,'endMinute',end_at,'teacherId',pg_temp.tid(101),'classroomId',pg_temp.tid(201),'sourceSlotId',null)))$$;
select set_config('request.jwt.claim.sub',pg_temp.tid(901)::text,true);
set local role authenticated;
select lives_ok($$select public.mutate_timetable_plan_v1(jsonb_build_object('operation','create','planId',pg_temp.tid(1),'name','첫 계획','requestKey','create'))$$,'admin creates independent empty plan');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(1))->'slots'),0,'empty board is readable');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(1))#>'{catalogs,teachers}'),(select count(*)::int from public.teacher_catalogs),'full catalogs support empty boards');
create temporary table first_result as select public.mutate_timetable_plan_item_v1(pg_temp.cmd(11)) as result;
select is(public.mutate_timetable_plan_item_v1(pg_temp.cmd(11)),(select result from first_result),'same actor and key replay exact result');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(11)||jsonb_build_object('item',(pg_temp.cmd(11)->'item')||'{"name":"다른 이름"}'::jsonb))$$,'22023','timetable_invalid','same key different body rejected');
select is((public.get_timetable_plan_v1(pg_temp.tid(1))#>>'{plan,metaRevision}')::int,0,'item save does not increment metadata revision');
select lives_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(12,null,660,720,'second'))$$,'adjacent half-open placement and distinct item save succeed');
select lives_ok($$select public.mutate_timetable_plan_v1(jsonb_build_object('operation','create','planId',pg_temp.tid(4),'name','동일 자원 대안','requestKey','create4'))$$,'alternative plan created');
select lives_ok($$select public.mutate_timetable_plan_item_v1(jsonb_set(jsonb_set(jsonb_set(pg_temp.cmd(41,null,600,660,'same-resources-other-plan'),'{planId}',to_jsonb(pg_temp.tid(4))),'{item,planId}',to_jsonb(pg_temp.tid(4))),'{slots}',jsonb_build_array((pg_temp.cmd(41)->'slots'->0)||jsonb_build_object('planId',pg_temp.tid(4)))))$$,'identical teacher room and time in another plan is independent');
reset role;
select throws_ok($$insert into public.timetable_plan_slots(id,plan_id,item_id,weekday,start_minute,end_minute,teacher_catalog_id,classroom_catalog_id,teacher_name,classroom_name) values(pg_temp.tid(777),pg_temp.tid(1),pg_temp.tid(41),1,600,660,pg_temp.tid(101),pg_temp.tid(201),'t','r')$$,'23503',null,'composite FK rejects cross-plan item even for privileged insert');
set local role authenticated;
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(11,0,610,650,'stale'))$$,'P0001','timetable_stale','same-item stale revision rejected');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(13,null,630,690,'overlap'))$$,'23P01','timetable_resource_conflict','same plan teacher and room conflict rejected');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(13,null,720,780,'tamper')||jsonb_build_object('item',(pg_temp.cmd(13)->'item')||'{"state":"applied"}'::jsonb))$$,'22023','timetable_invalid','lifecycle field injection rejected');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(13,null,720,780,'duplicates')||jsonb_build_object('slots',(pg_temp.cmd(13)->'slots')||(pg_temp.cmd(13)->'slots')))$$,'22023','timetable_invalid','duplicate slot identity rejected');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(13,null,630,690,'room-only')||jsonb_build_object('slots',jsonb_build_array((pg_temp.cmd(13,null,630,690)->'slots'->0)||jsonb_build_object('teacherId',pg_temp.tid(102)))))$$,'23P01','timetable_resource_conflict','same room conflicts even with another teacher');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(13,null,630,690,'teacher-only')||jsonb_build_object('slots',jsonb_build_array((pg_temp.cmd(13,null,630,690)->'slots'->0)||jsonb_build_object('classroomId',pg_temp.tid(202)))))$$,'23P01','timetable_resource_conflict','same teacher conflicts even in another room');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(13,null,720,780,'same-item')||jsonb_build_object('slots',(pg_temp.cmd(13,null,720,780)->'slots')||jsonb_build_array((pg_temp.cmd(13,null,730,790)->'slots'->0)||jsonb_build_object('id',pg_temp.tid(114),'teacherId',pg_temp.tid(102),'classroomId',pg_temp.tid(202)))))$$,'23P01','timetable_resource_conflict','same item overlaps even when both resources differ');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(13,null,720,780,'stale-shadow')||'{"expectedShadowFingerprint":"old"}'::jsonb)$$,'P0001','timetable_stale','stale shadow fingerprint rejected');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(13,null,720,780,'source-tamper')||jsonb_build_object('item',(pg_temp.cmd(13)->'item')||jsonb_build_object('sourceClassId',pg_temp.tid(301))))$$,'22023','timetable_invalid','source provenance is server-owned');
select is((select change_sequence from public.timetable_invalidation_signals where plan_id=pg_temp.tid(1)),2::bigint,'per plan signal matches item changes');
reset role;
insert into public.classes(id,name,subject,grade,status,schedule_storage_mode,schedule_revision) values(pg_temp.tid(301),'다른 과목 운영','수학','중3','수강','normalized',2);
select set_config('app.class_schedule_mutation','release2-rpc',true);
insert into public.class_schedule_slots(id,class_id,weekday,start_time,end_time,teacher_catalog_id,teacher_name,classroom_catalog_id,classroom_name) values(pg_temp.tid(401),pg_temp.tid(301),1,'10:00','11:00',pg_temp.tid(101),'동일 이름',pg_temp.tid(201),'동일 이름');
set local role authenticated;
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(1))->'shadowSlots'),1,'all subjects contribute authoritative shadows');
select lives_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(11,1,600,660,'rename')||jsonb_build_object('item',(pg_temp.cmd(11)->'item')||'{"name":"운영 충돌 보존"}'::jsonb))$$,'name-only edit preserves newly conflicting original occupancy');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(13,null,610,650,'shadow'))$$,'23P01','timetable_resource_conflict','hidden subject operational shadow blocks new placement');
select lives_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(11,2,720,780,'repair'))$$,'safe repair moves out of unchanged live conflict');
reset role;
update public.teacher_catalogs set is_visible=false where id=pg_temp.tid(101);
set local role authenticated;
select lives_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(11,3,720,780,'hidden-rename'))$$,'hidden resource unchanged occupancy can be renamed');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(13,null,780,840,'hidden-new'))$$,'22023','timetable_invalid','hidden resource cannot acquire new occupancy');
reset role;
delete from public.class_schedule_slots where class_id=pg_temp.tid(301);
select set_config('app.class_close_mutation','v1',true);
update public.classes set status='종강' where id=pg_temp.tid(301);
delete from public.teacher_catalogs where id=pg_temp.tid(101);
set local role authenticated;
select is(public.get_timetable_plan_v1(pg_temp.tid(1))#>>'{slots,0,teacherId}',pg_temp.tid(101)::text,'deleted resource retains original stable UUID');
select lives_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(11,4,720,780,'deleted-rename'))$$,'deleted resource snapshot permits non-occupancy edit');

select lives_ok($$select public.mutate_timetable_plan_v1(jsonb_build_object('operation','create','planId',pg_temp.tid(2),'name','독립 계획','requestKey','create2'))$$,'second plan created independently');
select lives_ok($$select public.mutate_timetable_plan_item_v1(jsonb_set(jsonb_set(jsonb_set(pg_temp.cmd(21,null,660,720,'other-plan'),'{planId}',to_jsonb(pg_temp.tid(2))),'{item,planId}',to_jsonb(pg_temp.tid(2))),'{slots}',jsonb_build_array((pg_temp.cmd(21)->'slots'->0)||jsonb_build_object('planId',pg_temp.tid(2),'teacherId',pg_temp.tid(102),'classroomId',pg_temp.tid(202),'startMinute',660,'endMinute',720))))$$,'other plan has independent occupancy');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(13,null,800,860,'cross-plan')||jsonb_build_object('slots',jsonb_build_array((pg_temp.cmd(13)->'slots'->0)||jsonb_build_object('id',pg_temp.tid(121),'teacherId',pg_temp.tid(102),'classroomId',pg_temp.tid(202),'startMinute',800,'endMinute',860))))$$,'22023','timetable_invalid','another plan slot cannot be stolen');
select lives_ok($$select public.mutate_timetable_plan_v1(jsonb_build_object('operation','rename','planId',pg_temp.tid(1),'expectedMetaRevision',0,'name','변경한 계획','requestKey','rename-meta'))$$,'metadata rename changes own revision');
select is((public.get_timetable_plan_v1(pg_temp.tid(1))#>>'{items,0,revision}')::int,5,'metadata rename leaves item revision unchanged');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(11,6,720,780,'old-meta'))$$,'P0001','timetable_stale','old metadata guard rejects save');
select lives_ok($$select public.mutate_timetable_plan_v1(jsonb_build_object('operation','archive','planId',pg_temp.tid(1),'expectedMetaRevision',1,'requestKey','archive'))$$,'archive is metadata operation');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(11,6,720,780,'archived')||'{"expectedMetaRevision":2}'::jsonb)$$,'42501','timetable_forbidden','archived plans are readonly');
select lives_ok($$select public.mutate_timetable_plan_v1(jsonb_build_object('operation','restore','planId',pg_temp.tid(1),'expectedMetaRevision',2,'requestKey','restore'))$$,'restore plan');
reset role;
insert into dashboard_private.timetable_plan_transfers(id,request_key,actor_id,source_plan_id) values(pg_temp.tid(700),'synthetic-applied',pg_temp.tid(901),pg_temp.tid(1));
update public.timetable_plan_items set state='applied',applied_class_id=null,applied_transfer_id=pg_temp.tid(700),applied_at=now() where id=pg_temp.tid(12);
set local role authenticated;
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(1))->'slots'),1,'applied item whose source was deleted stays out of draft grid');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(1))->'appliedSnapshots'),1,'applied snapshot remains separate after applied class ID becomes null');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(12,1,660,720,'applied-edit')||'{"expectedMetaRevision":3}'::jsonb)$$,'42501','timetable_forbidden','applied item is immutable');
select lives_ok($$select public.mutate_timetable_plan_v1(jsonb_build_object('operation','clone','planId',pg_temp.tid(3),'sourcePlanId',pg_temp.tid(1),'expectedMetaRevision',3,'name','복제 계획','requestKey','clone'))$$,'clone preserves unavailable draft resources for repair');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(3))->'slots'),1,'whole clone copies draft slots only');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(3))->'appliedSnapshots'),0,'applied source clones to unplaced draft');
select ok(not exists(select 1 from public.timetable_plan_items where plan_id=pg_temp.tid(3) and id in(pg_temp.tid(11),pg_temp.tid(12))),'clone allocates new item IDs');
select ok(not exists(select 1 from public.timetable_plan_slots where plan_id=pg_temp.tid(3) and id in(pg_temp.tid(111),pg_temp.tid(112))),'clone allocates new slot IDs');
select lives_ok($$select public.mutate_timetable_plan_item_v1(jsonb_build_object('operation','delete','planId',pg_temp.tid(2),'itemId',pg_temp.tid(21),'expectedMetaRevision',0,'expectedItemRevision',1,'expectedShadowFingerprint',public.get_timetable_plan_revision_v1(pg_temp.tid(2))->>'shadowFingerprint','requestKey','delete'))$$,'explicit delete atomically removes item and slots');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(2))->'slots'),0,'delete removes its placements');
reset role;
insert into public.classes(id,name,subject,grade,status,schedule_storage_mode,schedule,teacher,room) values(pg_temp.tid(302),'legacy exact','영어','중1','수강','legacy','월 17:13-18:43, 수 18:43-19:43','다른 교사','다른 방');
set local role authenticated;
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(1))->'shadowSlots'),2,'complete comma-separated legacy schedule resolves both tokens');
select is((public.get_timetable_plan_v1(pg_temp.tid(1))#>>'{shadowSlots,0,startMinute}')::int,1033,'strict legacy reader keeps exact minutes');
select is(public.get_timetable_plan_v1(pg_temp.tid(1))#>>'{shadowSlots,0,teacherId}',pg_temp.tid(102)::text,'legacy exact name resolves stable catalog UUID');
select is((public.get_timetable_plan_v1(pg_temp.tid(1))->>'complete')::boolean,true,'valid legacy occupancy complete');
reset role;
update public.classes set schedule='일정 확인 필요' where id=pg_temp.tid(302);
set local role authenticated;
select is((public.get_timetable_plan_v1(pg_temp.tid(1))->>'complete')::boolean,false,'unparseable legacy occupancy fails closed');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(1))->'unresolvedOccupancies'),1,'unresolved class is visible as blocker');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(13,null,900,960,'incomplete')||jsonb_build_object('expectedMetaRevision',3,'slots',jsonb_build_array((pg_temp.cmd(13)->'slots'->0)||jsonb_build_object('teacherId',pg_temp.tid(102),'classroomId',pg_temp.tid(202),'startMinute',900,'endMinute',960))))$$,'23P01','timetable_resource_conflict','incomplete occupancy never becomes free time');
reset role;
select set_config('app.class_close_mutation','v1',true);
update public.classes set status='종강' where id=pg_temp.tid(302);
insert into public.timetable_plan_items(id,plan_id,name,subject) select pg_temp.tid(1000+n),pg_temp.tid(2),'capacity '||n,'영어' from generate_series(1,500) n;
set local role authenticated;
select is((public.get_timetable_plan_v1(pg_temp.tid(2))#>>'{capacity,itemCount}')::int,500,'500 items returned without truncation');
select throws_ok($$select public.mutate_timetable_plan_item_v1(jsonb_set(jsonb_set(pg_temp.cmd(21,null,660,720,'over-slot-capacity'),'{planId}',to_jsonb(pg_temp.tid(2))),'{item,planId}',to_jsonb(pg_temp.tid(2)))||jsonb_build_object('slots',(select jsonb_agg((pg_temp.cmd(21)->'slots'->0)||jsonb_build_object('id',pg_temp.tid(10000+n),'planId',pg_temp.tid(2))) from generate_series(1,2001) n)))$$,'22023','timetable_capacity','2001-slot request rejected with exact producer pair before item insertion');
select throws_ok($$select public.mutate_timetable_plan_item_v1(jsonb_set(jsonb_set(pg_temp.cmd(21,null,660,720,'over-capacity'),'{planId}',to_jsonb(pg_temp.tid(2))),'{item,planId}',to_jsonb(pg_temp.tid(2)))||'{"slots":[]}'::jsonb)$$,'22023','timetable_capacity','501st item explicitly rejected');
reset role;
insert into public.timetable_plan_items(id,plan_id,name,subject) values(pg_temp.tid(1600),pg_temp.tid(2),'capacity exceeded','영어');
insert into public.timetable_plan_slots(id,plan_id,item_id,weekday,start_minute,end_minute,teacher_catalog_id,classroom_catalog_id,teacher_name,classroom_name) select pg_temp.tid(2000+n),pg_temp.tid(2),pg_temp.tid(1001),1,600,660,pg_temp.tid(102),pg_temp.tid(202),'다른 교사','다른 방' from generate_series(1,2001) n;
set local role authenticated;
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(2))->'items'),501,'over-capacity read does not truncate items');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(2))->'slots'),2001,'over-capacity read does not truncate slots');
select is((public.get_timetable_plan_v1(pg_temp.tid(2))->>'complete')::boolean,false,'capacity overflow is explicitly incomplete');
select throws_ok($$select public.mutate_timetable_plan_v1(jsonb_build_object('operation','rename','planId',pg_temp.tid(2),'name','blocked','expectedMetaRevision',0,'requestKey','capacity-meta'))$$,'22023','timetable_capacity','over-capacity board mutations are blocked');
select 'CONTRACT_SNAPSHOT='||public.get_timetable_plan_v1(pg_temp.tid(1))::text;
select ok(exists(select 1 from jsonb_array_elements(public.get_timetable_plan_v1(pg_temp.tid(1))#>'{catalogs,teachers}') x where x->>'id'=pg_temp.tid(101)::text and (x->>'isMissing')::boolean and x->>'name'='동일 이름'),'deleted resource has explicit unavailable display metadata');

-- Review regression: UUID spelling must never allow two rows to silently upsert one identity.
reset role;
create function pg_temp.plan_write_state(pid uuid) returns jsonb language sql stable security definer set search_path='' as $$
select jsonb_build_object('plan',(select to_jsonb(p) from public.timetable_plans p where id=pid),'items',(select coalesce(jsonb_agg(to_jsonb(i) order by id),'[]') from public.timetable_plan_items i where plan_id=pid),'slots',(select coalesce(jsonb_agg(to_jsonb(s) order by id),'[]') from public.timetable_plan_slots s where plan_id=pid),'members',(select coalesce(jsonb_agg(to_jsonb(m) order by user_id),'[]') from public.timetable_plan_members m where plan_id=pid),'signal',(select to_jsonb(s) from public.timetable_invalidation_signals s where plan_id=pid),'receipts',(select coalesce(jsonb_agg(to_jsonb(r) order by actor_id,operation,request_key),'[]') from dashboard_private.timetable_plan_mutation_receipts r))
$$;
create function pg_temp.duplicate_uuid_command(i int, representation text) returns jsonb language sql as $$
select pg_temp.cmd(i,null,600+(i-51)*200,660+(i-51)*200,'duplicate-'||representation)||jsonb_build_object('planId',pg_temp.tid(5),'item',(pg_temp.cmd(i)->'item')||jsonb_build_object('planId',pg_temp.tid(5)),'slots',jsonb_build_array((pg_temp.cmd(i,null,600+(i-51)*200,660+(i-51)*200)->'slots'->0)||jsonb_build_object('planId',pg_temp.tid(5),'teacherId',pg_temp.tid(102),'classroomId',pg_temp.tid(202),'weekday',2),(pg_temp.cmd(i,null,700+(i-51)*200,760+(i-51)*200)->'slots'->0)||jsonb_build_object('id',case when representation='uppercase' then upper(pg_temp.tid(i+100)::text) else replace(pg_temp.tid(i+100)::text,'-','') end,'planId',pg_temp.tid(5),'teacherId',pg_temp.tid(102),'classroomId',pg_temp.tid(202),'weekday',2)))
$$;
set local role authenticated;
select public.mutate_timetable_plan_v1(jsonb_build_object('operation','create','planId',pg_temp.tid(5),'name','UUID 원자성','requestKey','create5'));
create temporary table uuid_before as select pg_temp.plan_write_state(pg_temp.tid(5)) as snapshot;
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.duplicate_uuid_command(51,'uppercase'))$$,'22023','timetable_invalid','uppercase UUID spelling cannot bypass duplicate slot identity');
select is(pg_temp.plan_write_state(pg_temp.tid(5)),(select snapshot from uuid_before),'mixed-case UUID rejection preserves all plan rows revisions signal and receipts');
truncate uuid_before;
insert into uuid_before select pg_temp.plan_write_state(pg_temp.tid(5));
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.duplicate_uuid_command(52,'compact'))$$,'22023','timetable_invalid','compact UUID spelling cannot bypass duplicate slot identity');
select is(pg_temp.plan_write_state(pg_temp.tid(5)),(select snapshot from uuid_before),'equivalent compact UUID rejection preserves all plan rows revisions signal and receipts');

-- Existing schedule writers emit per-slot resource details in parentheses.
reset role;
insert into public.teacher_catalogs(id,name,subjects) values(pg_temp.tid(103),'괄호 교사',array['영어팀']);
insert into public.classroom_catalogs(id,name,subjects) values(pg_temp.tid(203),'괄호 방',array['영어']);
insert into public.classes(id,name,subject,grade,status,schedule_storage_mode,schedule,teacher,room) values(pg_temp.tid(303),'슬롯별 다른 자원','영어','중1','수강','legacy',E'월 17:13-18:43 (다른 교사, 다른 방)\n수 09:10-10:40 (괄호 교사, 괄호 방)','여러 교사','여러 방');
set local role authenticated;
select public.mutate_timetable_plan_v1(jsonb_build_object('operation','create','planId',pg_temp.tid(6),'name','괄호 legacy','requestKey','create6'));
select is((public.get_timetable_plan_v1(pg_temp.tid(6))->>'complete')::boolean,true,'valid parenthesized legacy schedule has complete snapshot');
select is(public.get_timetable_plan_v1(pg_temp.tid(6))->'unresolvedOccupancies','[]'::jsonb,'per-slot parenthesized labels do not become global blockers');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(6))->'shadowSlots'),2,'both parenthesized legacy slots are materialized');
select is((public.get_timetable_plan_v1(pg_temp.tid(6))#>'{shadowSlots,0}') - 'id' - 'classRevision',jsonb_build_object('sourceSlotId',null,'classId',pg_temp.tid(303),'weekday',1,'startMinute',1033,'endMinute',1123,'teacherId',pg_temp.tid(102),'classroomId',pg_temp.tid(202)),'first legacy slot resolves its exact teacher room and minutes');
select is((public.get_timetable_plan_v1(pg_temp.tid(6))#>'{shadowSlots,1}') - 'id' - 'classRevision',jsonb_build_object('sourceSlotId',null,'classId',pg_temp.tid(303),'weekday',3,'startMinute',550,'endMinute',640,'teacherId',pg_temp.tid(103),'classroomId',pg_temp.tid(203)),'second legacy slot resolves a different teacher room and minutes');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(61,null,1050,1080,'parenthesized-teacher')||jsonb_build_object('planId',pg_temp.tid(6),'item',(pg_temp.cmd(61)->'item')||jsonb_build_object('planId',pg_temp.tid(6)),'slots',jsonb_build_array((pg_temp.cmd(61,null,1050,1080)->'slots'->0)||jsonb_build_object('planId',pg_temp.tid(6),'teacherId',pg_temp.tid(102),'classroomId',pg_temp.tid(203),'weekday',1))))$$,'23P01','timetable_resource_conflict','first per-slot teacher shadow blocks even in another room');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(62,null,570,600,'parenthesized-room')||jsonb_build_object('planId',pg_temp.tid(6),'item',(pg_temp.cmd(62)->'item')||jsonb_build_object('planId',pg_temp.tid(6)),'slots',jsonb_build_array((pg_temp.cmd(62,null,570,600)->'slots'->0)||jsonb_build_object('planId',pg_temp.tid(6),'teacherId',pg_temp.tid(102),'classroomId',pg_temp.tid(203),'weekday',3))))$$,'23P01','timetable_resource_conflict','second per-slot room shadow blocks even with another teacher');
select lives_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(63,null,600,660,'parenthesized-safe')||jsonb_build_object('planId',pg_temp.tid(6),'item',(pg_temp.cmd(63)->'item')||jsonb_build_object('planId',pg_temp.tid(6)),'slots',jsonb_build_array((pg_temp.cmd(63,null,600,660)->'slots'->0)||jsonb_build_object('planId',pg_temp.tid(6),'teacherId',pg_temp.tid(102),'classroomId',pg_temp.tid(203),'weekday',5))))$$,'parenthesized legacy shadows permit unrelated safe placement');
select * from finish();
rollback;
