begin;
select no_plan();
create function pg_temp.tid(n int) returns uuid language sql immutable as $$select ('a7230000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
insert into auth.users(id,instance_id,aud,role,email) select pg_temp.tid(n),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','transfer'||n||'@test.invalid' from generate_series(901,903) n;
insert into public.profiles(id,role,name) select pg_temp.tid(n),case n when 901 then 'admin' when 902 then 'teacher' else 'staff' end,'transfer actor'||n from generate_series(901,903) n on conflict(id) do update set role=excluded.role;
delete from public.teacher_catalogs where profile_id=pg_temp.tid(902);
insert into public.teacher_catalogs(id,name,subjects,profile_id) values(pg_temp.tid(101),'transfer teacher',array['영어'],pg_temp.tid(902));
update public.profiles set teacher_catalog_id=pg_temp.tid(101) where id=pg_temp.tid(902);
insert into public.classroom_catalogs(id,name,subjects) values(pg_temp.tid(201),'transfer room',array['영어']);
select set_config('request.jwt.claim.sub',pg_temp.tid(901)::text,true);
create function pg_temp.seed(n int, amount int default 4) returns uuid language plpgsql as $$
declare pid uuid:=pg_temp.tid(n); begin
 insert into public.timetable_plans(id,name,created_by) values(pid,'fixture-transfer-plan-'||n,pg_temp.tid(901));
 for j in 1..amount loop
 insert into public.timetable_plan_items(id,plan_id,name,subject,grade,capacity,tuition) values(pg_temp.tid(n*100+j),pid,'fixture-transfer-'||n||'-'||j,'영어','중2',12,100000);
 insert into public.timetable_plan_slots(id,plan_id,item_id,weekday,start_minute,end_minute,teacher_catalog_id,classroom_catalog_id,teacher_name,classroom_name)
 values(pg_temp.tid(n*100+j+50),pid,pg_temp.tid(n*100+j),0,60*j,60*j+30,pg_temp.tid(101),pg_temp.tid(201),'transfer teacher','transfer room');
 end loop;return pid; end $$;
create function pg_temp.req(n int, target int, mode text default 'copy', amount int default 1, conflict text default 'reject') returns jsonb language sql as $$
select jsonb_build_object('source',jsonb_build_object('kind','plan','planId',pg_temp.tid(n)),'target',case when target=0 then jsonb_build_object('kind','operational') else jsonb_build_object('kind','plan','planId',pg_temp.tid(target)) end,'mode',mode,'onConflict',conflict,'itemIds',(select jsonb_agg(pg_temp.tid(n*100+j)) from generate_series(1,amount) j)) $$;
create function pg_temp.command(r jsonb,k text) returns jsonb language sql as $$select jsonb_build_object('request',r,'previewFingerprint',public.preview_timetable_plan_transfer_v1(r)->>'fingerprint','requestKey',k)$$;
create temp table saved(k text primary key, command jsonb, response jsonb);
grant all on saved to authenticated;
select has_function('public','preview_timetable_plan_transfer_v1',array['jsonb'],'transfer preview exists');
select has_function('public','commit_timetable_plan_transfer_v1',array['jsonb'],'atomic transfer exists');
select ok(not has_function_privilege('anon','public.commit_timetable_plan_transfer_v1(jsonb)','execute'),'anon denied');
select ok(not has_function_privilege('authenticated','dashboard_private.evaluate_timetable_transfer_v1(jsonb)','execute'),'private evaluator denied');
select pg_temp.seed(1);select pg_temp.seed(2,0);
set local role authenticated;
select throws_ok($$select public.preview_timetable_plan_transfer_v1(pg_temp.req(1,1))$$,'22023','timetable_invalid','same plan denied');
select throws_ok($$select public.preview_timetable_plan_transfer_v1(pg_temp.req(1,0)||jsonb_build_object('itemIds',jsonb_build_array(pg_temp.tid(101),pg_temp.tid(101))))$$,'22023','timetable_invalid','duplicate selection denied');
select throws_ok($$select public.preview_timetable_plan_transfer_v1(pg_temp.req(1,0,'copy',1,'keep_pending'))$$,'22023','timetable_invalid','operating keep_pending denied');
select throws_ok($$select public.preview_timetable_plan_transfer_v1(pg_temp.req(1,2,'move',1,'keep_pending'))$$,'22023','timetable_invalid','move keep_pending denied');
select throws_ok($$select public.preview_timetable_plan_transfer_v1(pg_temp.req(1,0)||'{"noConflict":true}')$$,'22023','timetable_invalid','client conflict bypass denied');
reset role;
-- Repeated matrix uses savepoints: every direction/mode/count starts identical.
savepoint matrix;
set local role authenticated;
insert into saved select '0-copy-1',pg_temp.command(pg_temp.req(1,0,'copy',1),'0-copy-1'),null;
update saved set response=public.commit_timetable_plan_transfer_v1(command) where k='0-copy-1';
select is(jsonb_array_length((select response->'mappings' from saved where k='0-copy-1')),1,'0-copy-1 all selected mappings');
select is(public.commit_timetable_plan_transfer_v1((select command from saved where k='0-copy-1')),(select response from saved where k='0-copy-1'),'0-copy-1 immutable replay');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(1)),4,'0-copy-1 source count');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(1))->'slots'),3,'0-copy-1 canonical source excludes applied');
select is((select count(*)::int from public.classes where name like 'fixture-transfer-%' and status='수강'),1,'0-copy-1 new active classes');
select ok(not exists(select 1 from public.classes where name like 'fixture-transfer-%' and (student_ids<>'[]'::jsonb or waitlist_ids<>'[]'::jsonb or textbook_ids<>'[]'::jsonb or textbook_usage<>'{}'::jsonb or lessons<>'[]'::jsonb)),'0-copy-1 no roster textbook history copied');
select is((select count(*)::int from public.class_lesson_sessions s join public.classes c on c.id=s.class_id where c.name like 'fixture-transfer-%'),0,'0-copy-1 no sessions generated');
reset role;
rollback to matrix;
savepoint matrix;
set local role authenticated;
insert into saved select '0-copy-3',pg_temp.command(pg_temp.req(1,0,'copy',3),'0-copy-3'),null;
update saved set response=public.commit_timetable_plan_transfer_v1(command) where k='0-copy-3';
select is(jsonb_array_length((select response->'mappings' from saved where k='0-copy-3')),3,'0-copy-3 all selected mappings');
select is(public.commit_timetable_plan_transfer_v1((select command from saved where k='0-copy-3')),(select response from saved where k='0-copy-3'),'0-copy-3 immutable replay');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(1)),4,'0-copy-3 source count');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(1))->'slots'),1,'0-copy-3 canonical source excludes applied');
select is((select count(*)::int from public.classes where name like 'fixture-transfer-%' and status='수강'),3,'0-copy-3 new active classes');
select ok(not exists(select 1 from public.classes where name like 'fixture-transfer-%' and (student_ids<>'[]'::jsonb or waitlist_ids<>'[]'::jsonb or textbook_ids<>'[]'::jsonb or textbook_usage<>'{}'::jsonb or lessons<>'[]'::jsonb)),'0-copy-3 no roster textbook history copied');
select is((select count(*)::int from public.class_lesson_sessions s join public.classes c on c.id=s.class_id where c.name like 'fixture-transfer-%'),0,'0-copy-3 no sessions generated');
reset role;
rollback to matrix;
savepoint matrix;
set local role authenticated;
insert into saved select '0-copy-4',pg_temp.command(pg_temp.req(1,0,'copy',4),'0-copy-4'),null;
update saved set response=public.commit_timetable_plan_transfer_v1(command) where k='0-copy-4';
select is(jsonb_array_length((select response->'mappings' from saved where k='0-copy-4')),4,'0-copy-4 all selected mappings');
select is(public.commit_timetable_plan_transfer_v1((select command from saved where k='0-copy-4')),(select response from saved where k='0-copy-4'),'0-copy-4 immutable replay');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(1)),4,'0-copy-4 source count');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(1))->'slots'),0,'0-copy-4 canonical source excludes applied');
select is((select count(*)::int from public.classes where name like 'fixture-transfer-%' and status='수강'),4,'0-copy-4 new active classes');
select ok(not exists(select 1 from public.classes where name like 'fixture-transfer-%' and (student_ids<>'[]'::jsonb or waitlist_ids<>'[]'::jsonb or textbook_ids<>'[]'::jsonb or textbook_usage<>'{}'::jsonb or lessons<>'[]'::jsonb)),'0-copy-4 no roster textbook history copied');
select is((select count(*)::int from public.class_lesson_sessions s join public.classes c on c.id=s.class_id where c.name like 'fixture-transfer-%'),0,'0-copy-4 no sessions generated');
reset role;
rollback to matrix;
savepoint matrix;
set local role authenticated;
insert into saved select '0-move-1',pg_temp.command(pg_temp.req(1,0,'move',1),'0-move-1'),null;
update saved set response=public.commit_timetable_plan_transfer_v1(command) where k='0-move-1';
select is(jsonb_array_length((select response->'mappings' from saved where k='0-move-1')),1,'0-move-1 all selected mappings');
select is(public.commit_timetable_plan_transfer_v1((select command from saved where k='0-move-1')),(select response from saved where k='0-move-1'),'0-move-1 immutable replay');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(1)),3,'0-move-1 source count');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(1))->'slots'),3,'0-move-1 canonical source excludes applied');
select is((select count(*)::int from public.classes where name like 'fixture-transfer-%' and status='수강'),1,'0-move-1 new active classes');
select ok(not exists(select 1 from public.classes where name like 'fixture-transfer-%' and (student_ids<>'[]'::jsonb or waitlist_ids<>'[]'::jsonb or textbook_ids<>'[]'::jsonb or textbook_usage<>'{}'::jsonb or lessons<>'[]'::jsonb)),'0-move-1 no roster textbook history copied');
select is((select count(*)::int from public.class_lesson_sessions s join public.classes c on c.id=s.class_id where c.name like 'fixture-transfer-%'),0,'0-move-1 no sessions generated');
reset role;
rollback to matrix;
savepoint matrix;
set local role authenticated;
insert into saved select '0-move-3',pg_temp.command(pg_temp.req(1,0,'move',3),'0-move-3'),null;
update saved set response=public.commit_timetable_plan_transfer_v1(command) where k='0-move-3';
select is(jsonb_array_length((select response->'mappings' from saved where k='0-move-3')),3,'0-move-3 all selected mappings');
select is(public.commit_timetable_plan_transfer_v1((select command from saved where k='0-move-3')),(select response from saved where k='0-move-3'),'0-move-3 immutable replay');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(1)),1,'0-move-3 source count');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(1))->'slots'),1,'0-move-3 canonical source excludes applied');
select is((select count(*)::int from public.classes where name like 'fixture-transfer-%' and status='수강'),3,'0-move-3 new active classes');
select ok(not exists(select 1 from public.classes where name like 'fixture-transfer-%' and (student_ids<>'[]'::jsonb or waitlist_ids<>'[]'::jsonb or textbook_ids<>'[]'::jsonb or textbook_usage<>'{}'::jsonb or lessons<>'[]'::jsonb)),'0-move-3 no roster textbook history copied');
select is((select count(*)::int from public.class_lesson_sessions s join public.classes c on c.id=s.class_id where c.name like 'fixture-transfer-%'),0,'0-move-3 no sessions generated');
reset role;
rollback to matrix;
savepoint matrix;
set local role authenticated;
insert into saved select '0-move-4',pg_temp.command(pg_temp.req(1,0,'move',4),'0-move-4'),null;
update saved set response=public.commit_timetable_plan_transfer_v1(command) where k='0-move-4';
select is(jsonb_array_length((select response->'mappings' from saved where k='0-move-4')),4,'0-move-4 all selected mappings');
select is(public.commit_timetable_plan_transfer_v1((select command from saved where k='0-move-4')),(select response from saved where k='0-move-4'),'0-move-4 immutable replay');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(1)),0,'0-move-4 source count');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(1))->'slots'),0,'0-move-4 canonical source excludes applied');
select is((select count(*)::int from public.classes where name like 'fixture-transfer-%' and status='수강'),4,'0-move-4 new active classes');
select ok(not exists(select 1 from public.classes where name like 'fixture-transfer-%' and (student_ids<>'[]'::jsonb or waitlist_ids<>'[]'::jsonb or textbook_ids<>'[]'::jsonb or textbook_usage<>'{}'::jsonb or lessons<>'[]'::jsonb)),'0-move-4 no roster textbook history copied');
select is((select count(*)::int from public.class_lesson_sessions s join public.classes c on c.id=s.class_id where c.name like 'fixture-transfer-%'),0,'0-move-4 no sessions generated');
reset role;
rollback to matrix;
savepoint matrix;
set local role authenticated;
insert into saved select '2-copy-1',pg_temp.command(pg_temp.req(1,2,'copy',1),'2-copy-1'),null;
update saved set response=public.commit_timetable_plan_transfer_v1(command) where k='2-copy-1';
select is(jsonb_array_length((select response->'mappings' from saved where k='2-copy-1')),1,'2-copy-1 all selected mappings');
select is(public.commit_timetable_plan_transfer_v1((select command from saved where k='2-copy-1')),(select response from saved where k='2-copy-1'),'2-copy-1 immutable replay');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(1)),4,'2-copy-1 source count');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(1))->'slots'),4,'2-copy-1 canonical source excludes applied');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(2) and state='draft'),1,'2-copy-1 destination stays draft');
select ok(not exists(select 1 from public.timetable_plan_slots where plan_id=pg_temp.tid(2) and id in(select id from public.timetable_plan_slots where plan_id=pg_temp.tid(1))),'2-copy-1 independent new slot IDs');
reset role;
rollback to matrix;
savepoint matrix;
set local role authenticated;
insert into saved select '2-copy-3',pg_temp.command(pg_temp.req(1,2,'copy',3),'2-copy-3'),null;
update saved set response=public.commit_timetable_plan_transfer_v1(command) where k='2-copy-3';
select is(jsonb_array_length((select response->'mappings' from saved where k='2-copy-3')),3,'2-copy-3 all selected mappings');
select is(public.commit_timetable_plan_transfer_v1((select command from saved where k='2-copy-3')),(select response from saved where k='2-copy-3'),'2-copy-3 immutable replay');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(1)),4,'2-copy-3 source count');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(1))->'slots'),4,'2-copy-3 canonical source excludes applied');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(2) and state='draft'),3,'2-copy-3 destination stays draft');
select ok(not exists(select 1 from public.timetable_plan_slots where plan_id=pg_temp.tid(2) and id in(select id from public.timetable_plan_slots where plan_id=pg_temp.tid(1))),'2-copy-3 independent new slot IDs');
reset role;
rollback to matrix;
savepoint matrix;
set local role authenticated;
insert into saved select '2-copy-4',pg_temp.command(pg_temp.req(1,2,'copy',4),'2-copy-4'),null;
update saved set response=public.commit_timetable_plan_transfer_v1(command) where k='2-copy-4';
select is(jsonb_array_length((select response->'mappings' from saved where k='2-copy-4')),4,'2-copy-4 all selected mappings');
select is(public.commit_timetable_plan_transfer_v1((select command from saved where k='2-copy-4')),(select response from saved where k='2-copy-4'),'2-copy-4 immutable replay');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(1)),4,'2-copy-4 source count');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(1))->'slots'),4,'2-copy-4 canonical source excludes applied');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(2) and state='draft'),4,'2-copy-4 destination stays draft');
select ok(not exists(select 1 from public.timetable_plan_slots where plan_id=pg_temp.tid(2) and id in(select id from public.timetable_plan_slots where plan_id=pg_temp.tid(1))),'2-copy-4 independent new slot IDs');
reset role;
rollback to matrix;
savepoint matrix;
set local role authenticated;
insert into saved select '2-move-1',pg_temp.command(pg_temp.req(1,2,'move',1),'2-move-1'),null;
update saved set response=public.commit_timetable_plan_transfer_v1(command) where k='2-move-1';
select is(jsonb_array_length((select response->'mappings' from saved where k='2-move-1')),1,'2-move-1 all selected mappings');
select is(public.commit_timetable_plan_transfer_v1((select command from saved where k='2-move-1')),(select response from saved where k='2-move-1'),'2-move-1 immutable replay');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(1)),3,'2-move-1 source count');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(1))->'slots'),3,'2-move-1 canonical source excludes applied');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(2) and state='draft'),1,'2-move-1 destination stays draft');
select ok(not exists(select 1 from public.timetable_plan_slots where plan_id=pg_temp.tid(2) and id in(select id from public.timetable_plan_slots where plan_id=pg_temp.tid(1))),'2-move-1 independent new slot IDs');
reset role;
rollback to matrix;
savepoint matrix;
set local role authenticated;
insert into saved select '2-move-3',pg_temp.command(pg_temp.req(1,2,'move',3),'2-move-3'),null;
update saved set response=public.commit_timetable_plan_transfer_v1(command) where k='2-move-3';
select is(jsonb_array_length((select response->'mappings' from saved where k='2-move-3')),3,'2-move-3 all selected mappings');
select is(public.commit_timetable_plan_transfer_v1((select command from saved where k='2-move-3')),(select response from saved where k='2-move-3'),'2-move-3 immutable replay');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(1)),1,'2-move-3 source count');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(1))->'slots'),1,'2-move-3 canonical source excludes applied');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(2) and state='draft'),3,'2-move-3 destination stays draft');
select ok(not exists(select 1 from public.timetable_plan_slots where plan_id=pg_temp.tid(2) and id in(select id from public.timetable_plan_slots where plan_id=pg_temp.tid(1))),'2-move-3 independent new slot IDs');
reset role;
rollback to matrix;
savepoint matrix;
set local role authenticated;
insert into saved select '2-move-4',pg_temp.command(pg_temp.req(1,2,'move',4),'2-move-4'),null;
update saved set response=public.commit_timetable_plan_transfer_v1(command) where k='2-move-4';
select is(jsonb_array_length((select response->'mappings' from saved where k='2-move-4')),4,'2-move-4 all selected mappings');
select is(public.commit_timetable_plan_transfer_v1((select command from saved where k='2-move-4')),(select response from saved where k='2-move-4'),'2-move-4 immutable replay');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(1)),0,'2-move-4 source count');
select is(jsonb_array_length(public.get_timetable_plan_v1(pg_temp.tid(1))->'slots'),0,'2-move-4 canonical source excludes applied');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(2) and state='draft'),4,'2-move-4 destination stays draft');
select ok(not exists(select 1 from public.timetable_plan_slots where plan_id=pg_temp.tid(2) and id in(select id from public.timetable_plan_slots where plan_id=pg_temp.tid(1))),'2-move-4 independent new slot IDs');
reset role;
rollback to matrix;

savepoint minutes;
update public.timetable_plan_slots set start_minute=1033,end_minute=1093 where item_id=pg_temp.tid(101);
update public.timetable_plan_slots set start_minute=1410,end_minute=1440 where item_id=pg_temp.tid(102);
insert into saved select 'minutes',pg_temp.command(pg_temp.req(1,0,'copy',2),'minutes'),null;
update saved set response=public.commit_timetable_plan_transfer_v1(command) where k='minutes';
select is((select start_time from public.class_schedule_slots where class_id=(select (response#>>'{mappings,0,targetClassId}')::uuid from saved where k='minutes')),'17:13'::time,'transfer preserves 17:13 exactly');
select is((select end_time from public.class_schedule_slots where class_id=(select (response#>>'{mappings,1,targetClassId}')::uuid from saved where k='minutes')),'24:00'::time,'transfer preserves endMinute1440 as 24:00');
select is((select x->>'endMinute' from saved,jsonb_array_elements(response->'addedShadowSlots') x where k='minutes' and x->>'classId'=response#>>'{mappings,1,targetClassId}'),'1440','canonical promoted shadow retains endMinute1440');
rollback to minutes;
-- Unselected unresolved drafts must not block a valid promotion.
update public.timetable_plan_items set pending_slots='[{"id":"a7230000-0000-4000-8000-000000000099","sourceText":"원문 미정 17:13","reason":"invalid_time","weekday":null,"startMinute":null,"endMinute":null,"teacherId":null,"classroomId":null}]' where id=pg_temp.tid(104);
delete from public.timetable_plan_slots where item_id=pg_temp.tid(103);
select is(jsonb_array_length(public.preview_timetable_plan_transfer_v1(pg_temp.req(1,0))->'blockers'),0,'unselected pending/zero slots ignored');
select is(jsonb_array_length(public.preview_timetable_plan_transfer_v1(pg_temp.req(1,0,'copy',4))->'blockers'),2,'pending and zero slot rejected for whole promotion');
select is(jsonb_array_length(public.preview_timetable_plan_transfer_v1(pg_temp.req(1,2,'move',4))->'blockers'),2,'all moves reject pending and zero slots');
insert into saved select 'keep',pg_temp.command(pg_temp.req(1,2,'copy',4,'keep_pending'),'keep'),null;
update saved set response=public.commit_timetable_plan_transfer_v1(command) where k='keep';
select is((select pending_slots from public.timetable_plan_items where plan_id=pg_temp.tid(2) and name='fixture-transfer-1-4'),(select pending_slots from public.timetable_plan_items where id=pg_temp.tid(104)),'keep_pending preserves complete unresolved original');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(2)),4,'keep_pending copies zero slot item too');
select is(jsonb_array_length(public.preview_timetable_plan_transfer_v1(pg_temp.req(1,2))->'blockers'),1,'destination existing draft conflicts');
insert into saved select 'conflict-copy',pg_temp.command(pg_temp.req(1,2,'copy',1,'keep_pending'),'conflict-copy'),null;
update saved set response=public.commit_timetable_plan_transfer_v1(command) where k='conflict-copy';
select is(jsonb_array_length((select response#>'{createdItems,0,pendingSlots}' from saved where k='conflict-copy')),1,'conflicting confirmed slot becomes pending');
select is((select response#>>'{createdItems,0,pendingSlots,0,startMinute}' from saved where k='conflict-copy'),'60','pending retains original exact minutes');
select is(jsonb_array_length((select response->'createdSlots' from saved where k='conflict-copy')),0,'conflict copy never inserts occupied confirmed slot');
-- Converting conflicts cannot exceed the existing per-item pending save limit.
savepoint pending_capacity;
update public.timetable_plan_items set pending_slots=(select jsonb_agg(jsonb_build_object('id',gen_random_uuid(),'sourceText','unresolved','reason','conflict','weekday',null,'startMinute',null,'endMinute',null,'teacherId',null,'classroomId',null)) from generate_series(1,2000)) where id=pg_temp.tid(101);
select throws_ok($$select public.preview_timetable_plan_transfer_v1(pg_temp.req(1,2,'copy',1,'keep_pending'))$$,'22023','timetable_capacity','conflict conversion respects per-item pending capacity');
rollback to pending_capacity;
-- Catalog, destination revisions and sharing invalidate preview.
insert into saved select 'stale',pg_temp.command(pg_temp.req(1,0),'stale'),null;
update public.teacher_catalogs set is_visible=false where id=pg_temp.tid(101);
select throws_ok($$select public.commit_timetable_plan_transfer_v1((select command from saved where k='stale'))$$,'P0001','timetable_stale','catalog hiding invalidates preview');
select is(public.preview_timetable_plan_transfer_v1(pg_temp.req(1,0))#>>'{blockers,0,code}','missing_resource','hidden catalog explicit blocker');
update public.teacher_catalogs set is_visible=true where id=pg_temp.tid(101);
insert into public.timetable_plan_members(plan_id,user_id,access) values(pg_temp.tid(1),pg_temp.tid(902),'editor'),(pg_temp.tid(2),pg_temp.tid(902),'editor');
select set_config('request.jwt.claim.sub',pg_temp.tid(902)::text,true);
select throws_ok($$select public.preview_timetable_plan_transfer_v1(pg_temp.req(1,0))$$,'42501','timetable_forbidden','editor cannot promote');
insert into saved select 'editor',pg_temp.command(pg_temp.req(1,2,'copy',1,'keep_pending'),'editor'),null;
savepoint editor_replay;
update saved set response=public.commit_timetable_plan_transfer_v1(command) where k='editor';
select is((select jsonb_array_length(response->'createdItems') from saved where k='editor'),1,'eligible editor copies into authorized destination');
delete from public.timetable_plan_members where plan_id=pg_temp.tid(2);
select throws_ok($$select public.commit_timetable_plan_transfer_v1((select command from saved where k='editor'))$$,'42501','timetable_forbidden','permission revocation also denies immutable receipt replay');
rollback to editor_replay;
delete from public.timetable_plan_members where plan_id=pg_temp.tid(2);
select throws_ok($$select public.commit_timetable_plan_transfer_v1((select command from saved where k='editor'))$$,'42501','timetable_forbidden','destination share revoked before commit');
select set_config('request.jwt.claim.sub',pg_temp.tid(901)::text,true);
-- Last-class failure proves all-or-none including source and both receipt tables.
create function pg_temp.fail_last() returns trigger language plpgsql as $$begin if new.name='fixture-transfer-1-2' then raise exception 'fixture_last_insert'; end if;return new;end$$;
create trigger fixture_transfer_fail before insert on public.classes for each row execute function pg_temp.fail_last();
insert into saved select 'fail',pg_temp.command(pg_temp.req(1,0,'move',2),'fail'),null;
select throws_ok($$select public.commit_timetable_plan_transfer_v1((select command from saved where k='fail'))$$,'P0001','fixture_last_insert','last insert fails batch');
select is((select count(*)::int from public.classes where name like 'fixture-transfer-%'),0,'rollback leaves no new classes');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(1)),4,'rollback preserves all source items');
select is((select count(*)::int from dashboard_private.timetable_plan_transfers where request_key='fail'),0,'rollback removes audit receipt');
select is((select count(*)::int from dashboard_private.timetable_plan_mutation_receipts where request_key='fail'),0,'rollback removes mutation receipt');
insert into saved select 'fail-copy',pg_temp.command(pg_temp.req(1,0,'copy',2),'fail-copy'),null;
select throws_ok($$select public.commit_timetable_plan_transfer_v1((select command from saved where k='fail-copy'))$$,'P0001','fixture_last_insert','copy last insert fails whole batch');
select is((select count(*)::int from public.timetable_plan_items where plan_id=pg_temp.tid(1) and state='applied'),0,'failed copy rolls back earlier applied update');
select is((select count(*)::int from public.classes where name like 'fixture-transfer-%'),0,'failed copy leaves no created classes');
select is((select count(*)::int from dashboard_private.timetable_plan_transfers where request_key='fail-copy'),0,'failed copy removes audit receipt');
drop trigger fixture_transfer_fail on public.classes;
-- Actual future session blocks promotion even when its class is not active.
insert into public.classes(id,name,subject,grade,status,schedule_storage_mode) values(pg_temp.tid(800),'fixture-transfer-session-owner','영어','중2','개강 준비','normalized');
select set_config('app.class_schedule_mutation','release2-rpc',true);
insert into public.class_lesson_sessions(id,class_id,session_date,start_time,end_time,teacher_catalog_id,teacher_name_snapshot,classroom_catalog_id,classroom_name_snapshot,schedule_state,session_key,origin)
 values(pg_temp.tid(801),pg_temp.tid(800),(current_date+14-extract(dow from current_date)::int),'01:00','01:30',pg_temp.tid(101),'transfer teacher',pg_temp.tid(201),'transfer room','active','transfer-session','manual');
select is(public.preview_timetable_plan_transfer_v1(pg_temp.req(1,0))#>>'{blockers,0,code}','conflict','future actual session blocks operating promotion');
update public.class_lesson_sessions set schedule_state='skipped' where id=pg_temp.tid(801);
select is(jsonb_array_length(public.preview_timetable_plan_transfer_v1(pg_temp.req(1,0))->'blockers'),0,'skipped actual session has no occupancy');
insert into saved select 'session-change',pg_temp.command(pg_temp.req(1,0),'session-change'),null;
update public.class_lesson_sessions set schedule_state='active' where id=pg_temp.tid(801);
select throws_ok($$select public.commit_timetable_plan_transfer_v1((select command from saved where k='session-change'))$$,'P0001','timetable_stale','dated session change invalidates commit');
update public.class_lesson_sessions set schedule_state='skipped' where id=pg_temp.tid(801);
insert into saved select 'target-change',pg_temp.command(pg_temp.req(1,2,'copy',1,'keep_pending'),'target-change'),null;
update public.timetable_plans set meta_revision=meta_revision+1,name='changed target' where id=pg_temp.tid(2);
select throws_ok($$select public.commit_timetable_plan_transfer_v1((select command from saved where k='target-change'))$$,'P0001','timetable_stale','target revision invalidates preview');
insert into public.students(id,name,status,class_ids) values(pg_temp.tid(810),'fixture transfer student','재원',jsonb_build_array(pg_temp.tid(800)));
update public.classes set student_ids=jsonb_build_array(pg_temp.tid(810)) where id=pg_temp.tid(800);
insert into public.student_class_enrollment_history(student_id,class_id,action,previous_mode) values(pg_temp.tid(810),pg_temp.tid(800),'removed','enrolled');
-- Capture all existing operating and roster/history/session data, not just a count.
create temp table invariant_before as select jsonb_build_object(
 'classes',(select jsonb_agg(to_jsonb(c) order by id) from public.classes c),
 'students',(select jsonb_agg(to_jsonb(s) order by id) from public.students s),
 'history',(select jsonb_agg(to_jsonb(h) order by id) from public.student_class_enrollment_history h),
 'sessions',(select jsonb_agg(to_jsonb(s) order by id) from public.class_lesson_sessions s)) body;
-- Copy promotion is single use; replay after new operating changes stays immutable.
insert into saved select 'promote',pg_temp.command(pg_temp.req(1,0),'promote'),null;
update saved set response=public.commit_timetable_plan_transfer_v1(command) where k='promote';
select is((select jsonb_agg(to_jsonb(c) order by id) from public.classes c where id not in(select (x->>'targetClassId')::uuid from saved,jsonb_array_elements(response->'mappings') x where k='promote')),(select body->'classes' from invariant_before),'all pre-existing classes remain byte equivalent');
select is((select jsonb_agg(to_jsonb(s) order by id) from public.students s),(select body->'students' from invariant_before),'student states remain unchanged');
select is((select jsonb_agg(to_jsonb(h) order by id) from public.student_class_enrollment_history h),(select body->'history' from invariant_before),'enrollment histories remain unchanged');
select is((select jsonb_agg(to_jsonb(s) order by id) from public.class_lesson_sessions s),(select body->'sessions' from invariant_before),'all pre-existing sessions remain unchanged');
select throws_ok($$select public.preview_timetable_plan_transfer_v1(pg_temp.req(1,0))$$,'22023','timetable_invalid','applied item cannot promote with new key');
select is((select state from public.timetable_plan_items where id=pg_temp.tid(101)),'applied','source copy retained as applied');
select ok(exists(select 1 from jsonb_array_elements(public.get_timetable_plan_v1(pg_temp.tid(2))->'shadowClasses') x where x->>'name'='fixture-transfer-1-1'),'other plans see new labeled shadow');
create temp table operating_before as select to_jsonb(c) body from public.classes c where name='fixture-transfer-1-1';
update public.timetable_plan_items set source_class_id=(select id from public.classes where name='fixture-transfer-1-1') where id=pg_temp.tid(102);
update public.timetable_plan_slots set start_minute=60,end_minute=90 where item_id=pg_temp.tid(102);
select is(public.preview_timetable_plan_transfer_v1(pg_temp.req(1,0)||jsonb_build_object('itemIds',jsonb_build_array(pg_temp.tid(102))))#>>'{blockers,0,code}','conflict','source_class_id never excludes operating shadow');
select is((select to_jsonb(c) from public.classes c where name='fixture-transfer-1-1'),(select body from operating_before),'existing operating class remains byte equivalent');
select set_config('app.class_close_mutation','v1',true);
update public.classes set status='종강' where name='fixture-transfer-1-1';
select is(public.commit_timetable_plan_transfer_v1((select command from saved where k='promote')),(select response from saved where k='promote'),'replay after closing returns original immutable result');
-- Existing audit DELETE FK defect is isolated here; this proves FK lifecycle only.
delete from public.class_schedule_slots where class_id=(select id from public.classes where name='fixture-transfer-1-1');
alter table public.classes disable trigger dashboard_audit_classes;
delete from public.classes where name='fixture-transfer-1-1';
alter table public.classes enable trigger dashboard_audit_classes;
select is((select tgenabled::text from pg_trigger where tgrelid='public.classes'::regclass and tgname='dashboard_audit_classes'),'O','audit trigger restored inside rollback-only fixture');
select is((select state from public.timetable_plan_items where id=pg_temp.tid(101)),'applied','FK null never revives applied draft');
select is((select applied_class_id from public.timetable_plan_items where id=pg_temp.tid(101)),null::uuid,'deleted class clears only FK');
select throws_ok($$select public.commit_timetable_plan_transfer_v1((select command||'{"previewFingerprint":"changed"}' from saved where k='promote'))$$,'22023','timetable_invalid','same key body mutation rejected');
select * from finish();
rollback;
