begin;
do $$begin
 if not exists(select 1 from pg_catalog.pg_extension where extname='pgtap') then
  create extension pgtap with schema extensions;
 end if;
end $$;
select no_plan();
create function pg_temp.tid(n int) returns uuid language sql immutable as $$select ('ac239000-0000-4000-8000-'||lpad(n::text,12,'0'))::uuid$$;
insert into auth.users(id,instance_id,aud,role,email,raw_app_meta_data,raw_user_meta_data,created_at,updated_at)
select pg_temp.tid(n),'00000000-0000-0000-0000-000000000000','authenticated','authenticated','plan'||n||'@test.invalid','{}','{}',now(),now() from generate_series(901,905) n;
insert into public.profiles(id,role,name,email) select pg_temp.tid(n),case n when 901 then 'admin' when 902 then 'staff' when 905 then 'assistant' else 'teacher' end,'plan actor '||n,'plan'||n||'@test.invalid' from generate_series(901,905) n on conflict(id) do update set role=excluded.role;
delete from public.teacher_catalogs where profile_id in(pg_temp.tid(903),pg_temp.tid(904));
insert into public.teacher_catalogs(id,name,subjects,profile_id) values(pg_temp.tid(101),'동일 이름',array['영어팀'],pg_temp.tid(903)),(pg_temp.tid(102),'다른 교사',array['영어'],pg_temp.tid(904));
update public.profiles set teacher_catalog_id=case id when pg_temp.tid(903) then pg_temp.tid(101) else pg_temp.tid(102) end where id in(pg_temp.tid(903),pg_temp.tid(904));
insert into public.classroom_catalogs(id,name,subjects) values(pg_temp.tid(201),'동일 이름',array['영어']),(pg_temp.tid(202),'다른 방',array['영어']);
create function pg_temp.cmd(i int, rev int default null, start_at int default 600, end_at int default 660, k text default 'save') returns jsonb language sql as $$select jsonb_build_object('operation','save','planId',pg_temp.tid(1),'expectedMetaRevision',0,'expectedShadowFingerprint',public.get_timetable_plan_revision_v1(pg_temp.tid(1))->>'shadowFingerprint','expectedItemRevision',rev,'requestKey',k,'item',jsonb_build_object('id',pg_temp.tid(i),'planId',pg_temp.tid(1),'name','초안','subject','영어','subjectAreaKey',null,'grade','중2','capacity',12,'tuition',100000,'defaultTeacherId',pg_temp.tid(101),'defaultClassroomId',pg_temp.tid(201),'durationMinutes',60,'pendingSlots','[]'::jsonb),'slots',jsonb_build_array(jsonb_build_object('id',pg_temp.tid(i+100),'itemId',pg_temp.tid(i),'planId',pg_temp.tid(1),'weekday',1,'startMinute',start_at,'endMinute',end_at,'teacherId',pg_temp.tid(101),'classroomId',pg_temp.tid(201),'sourceSlotId',null)))$$;
select set_config('request.jwt.claim.sub',pg_temp.tid(901)::text,true);
set local role authenticated;
select lives_ok($$select public.mutate_timetable_plan_v1(jsonb_build_object('operation','create','planId',pg_temp.tid(1),'name','공유 계획','requestKey','create'))$$,'create plan');
select throws_ok($$insert into public.timetable_plans(name,created_by,updated_by) values('bypass',pg_temp.tid(901),pg_temp.tid(901))$$,'42501',null,'direct table writes denied');
select lives_ok($$select public.mutate_timetable_plan_v1(jsonb_build_object('operation','share','planId',pg_temp.tid(1),'expectedMetaRevision',0,'members',jsonb_build_array(jsonb_build_object('userId',pg_temp.tid(903),'access','editor')),'requestKey','share'))$$,'admin shares only linked teacher');
select set_config('request.jwt.claim.sub',pg_temp.tid(903)::text,true);
select lives_ok($$select public.get_timetable_plan_v1(pg_temp.tid(1))$$,'shared teacher reads plan');
select lives_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(11)||'{"expectedMetaRevision":1}'::jsonb)$$,'shared editor edits draft');
select throws_ok($$select public.mutate_timetable_plan_v1(jsonb_build_object('operation','archive','planId',pg_temp.tid(1),'expectedMetaRevision',1,'requestKey','bad-archive'))$$,'42501','timetable_forbidden','teacher cannot manage metadata');
select set_config('request.jwt.claim.sub',pg_temp.tid(904)::text,true);
select throws_ok($$select public.get_timetable_plan_v1(pg_temp.tid(1))$$,'42501','timetable_forbidden','unshared teacher cannot read');
select is((select count(*) from public.timetable_plan_items),0::bigint,'RLS hides items from unshared teacher');
select is((select count(*) from public.timetable_invalidation_signals where plan_id=pg_temp.tid(1)),0::bigint,'RLS hides plan invalidation from unshared teacher');
select set_config('request.jwt.claim.sub',pg_temp.tid(901)::text,true);
select public.mutate_timetable_plan_v1(jsonb_build_object('operation','share','planId',pg_temp.tid(1),'expectedMetaRevision',1,'members','[]'::jsonb,'requestKey','revoke'));
select set_config('request.jwt.claim.sub',pg_temp.tid(903)::text,true);
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(11)||'{"expectedMetaRevision":1}'::jsonb)$$,'42501','timetable_forbidden','revoked editor cannot replay old receipt');
select set_config('request.jwt.claim.sub',pg_temp.tid(902)::text,true);
select lives_ok($$select public.get_timetable_plan_v1(pg_temp.tid(1))$$,'staff access without membership');
select set_config('request.jwt.claim.sub','',true);
set local role anon;
select throws_ok($$select public.get_timetable_plan_v1(pg_temp.tid(1))$$,'42501',null,'anon RPC execute denied');
select throws_ok($$select * from public.timetable_plans$$,'42501',null,'anon table select denied');
reset role;

select set_config('request.jwt.claim.sub',pg_temp.tid(901)::text,true);
set local role authenticated;
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(11)||'{"expectedMetaRevision":2}'::jsonb)$$,'P0001','timetable_stale','same request key from another actor cannot expose original receipt');
select is(jsonb_array_length(public.list_timetable_share_candidates_v1()),2,'share candidates contain eligible linked teachers only');
select throws_ok($$select dashboard_private.read_timetable_operating_reference_v1()$$,'42501',null,'private reader cannot be called directly');
select throws_ok($$select * from dashboard_private.timetable_plan_mutation_receipts$$,'42501',null,'receipts are private');
select throws_ok($$update public.timetable_invalidation_signals set change_sequence=999$$,'42501',null,'client cannot forge invalidation events');
select throws_ok($$select public.mutate_timetable_plan_v1(jsonb_build_object('operation','share','planId',pg_temp.tid(1),'expectedMetaRevision',2,'members',jsonb_build_array(jsonb_build_object('userId',pg_temp.tid(905),'access','editor')),'requestKey','assistant'))$$,'22023','timetable_invalid','assistant cannot be shared by teacher membership');
select public.mutate_timetable_plan_v1(jsonb_build_object('operation','share','planId',pg_temp.tid(1),'expectedMetaRevision',2,'members',jsonb_build_array(jsonb_build_object('userId',pg_temp.tid(904),'access','viewer')),'requestKey','viewer'));
select set_config('request.jwt.claim.sub',pg_temp.tid(904)::text,true);
select lives_ok($$select public.get_timetable_plan_v1(pg_temp.tid(1))$$,'shared viewer can read');
select throws_ok($$select public.mutate_timetable_plan_item_v1(pg_temp.cmd(11,1)||'{"expectedMetaRevision":3}'::jsonb)$$,'42501','timetable_forbidden','shared viewer cannot edit');
select throws_ok($$select public.list_timetable_share_candidates_v1()$$,'42501','timetable_forbidden','share candidates restricted to management');
select is((public.get_timetable_plan_v1(pg_temp.tid(1))#>>'{permissions,canEdit}')::boolean,false,'server permissions mark viewer readonly');
reset role;
update public.profiles set role='viewer' where id=pg_temp.tid(902);
select set_config('request.jwt.claim.sub',pg_temp.tid(902)::text,true);
set local role authenticated;
select throws_ok($$select public.get_timetable_plan_v1(pg_temp.tid(1))$$,'42501','timetable_forbidden','staff role revocation applies on next request');
reset role;
select * from finish();
rollback;
