/* eslint-disable @typescript-eslint/no-explicit-any -- strict transport checks narrow every RPC field. */
import { readTextbookPurpose, textbookPurposeValidation, type TextbookReadOptions } from "./textbook-read-service";
import { assertOwnerDraft } from "./textbook-owner-settings-model";
import type { OwnerCounts, OwnerSettingsDetail, OwnerSettingsPage, PublisherSettingRow, SettingPageRequest, SupplierSettingOption, SupplierSettingRow } from "./textbook-settings-types";

const v: typeof textbookPurposeValidation = textbookPurposeValidation;
type RecordValue = Record<string, any>;
const object = (value: unknown): value is RecordValue => value !== null && typeof value === "object" && !Array.isArray(value);
function exact(value: unknown, keys: string[]) { v.exact(value, keys); return value as RecordValue; }
function ownerCounts(value: unknown): OwnerCounts { const row = exact(value, ["publishers", "suppliers"]); if (!v.integer(row.publishers) || !v.integer(row.suppliers) || row.publishers < 0 || row.suppliers < 0) v.fail(); return row as OwnerCounts; }
function pageRequest(request: unknown): asserts request is SettingPageRequest {
  if (!object(request) || Object.keys(request).length !== 5 || !["page", "pageSize", "sort", "filters", "draft"].every(key => Object.prototype.hasOwnProperty.call(request, key)) || !v.integer(request.page) || request.page < 1 || request.page > 2147483647 || ![10, 15, 20].includes(request.pageSize as number) || request.sort !== "name") v.fail("input");
  exact(request.filters, ["search"]); if (typeof request.filters.search !== "string") v.fail("filters"); if (request.draft !== null) assertOwnerDraft(request.draft);
}
function publisher(value: unknown): PublisherSettingRow { const row = exact(value, ["id", "name", "subjects", "suppliers", "textbookCount", "isNew"]); if (!v.uuid(row.id) || typeof row.name !== "string" || !v.stringArray(row.subjects) || !v.integer(row.textbookCount) || row.textbookCount < 0 || typeof row.isNew !== "boolean" || !Array.isArray(row.suppliers)) v.fail(); const ids = new Set<string>(); row.suppliers.forEach(item => { const supplier = exact(item, ["id", "name"]); if (!v.uuid(supplier.id) || typeof supplier.name !== "string" || ids.has(supplier.id.toLowerCase())) v.fail(); ids.add(supplier.id.toLowerCase()); }); return row as PublisherSettingRow; }
function supplier(value: unknown): SupplierSettingRow { const row = exact(value, ["id", "name", "contact", "memo", "linkedPublisherCount", "linkedPublisherNames", "isNew"]); if (!v.uuid(row.id) || ![row.name, row.contact, row.memo].every(item => typeof item === "string") || !v.stringArray(row.linkedPublisherNames) || !v.integer(row.linkedPublisherCount) || row.linkedPublisherCount < 0 || row.linkedPublisherNames.length !== Math.min(3, row.linkedPublisherCount) || typeof row.isNew !== "boolean") v.fail(); return row as SupplierSettingRow; }
function option(value: unknown): SupplierSettingOption { const row = exact(value, ["id", "name"]); if (!v.uuid(row.id) || typeof row.name !== "string") v.fail(); return row as SupplierSettingOption; }
type OwnerKind = "publishers" | "suppliers";
function relationCounts(row: { id: string }, counts: OwnerCounts) { const value = row as unknown as RecordValue; if (Array.isArray(value.suppliers) && value.suppliers.length > counts.suppliers) v.fail(); if (Object.prototype.hasOwnProperty.call(value, "linkedPublisherCount") && (!v.integer(value.linkedPublisherCount) || value.linkedPublisherCount > counts.publishers)) v.fail(); }
function page<T extends { id: string }>(value: unknown, request: SettingPageRequest, parser: (row: unknown) => T, kind: OwnerKind): OwnerSettingsPage<T> { const row = exact(value, ["rows", "page", "pageSize", "totalCount", "baseRevision", "ownerCounts"]); if (row.page !== request.page || row.pageSize !== request.pageSize || !v.integer(row.totalCount) || row.totalCount < 0 || typeof row.baseRevision !== "string" || !/^[0-9a-f]{64}$/.test(row.baseRevision) || !Array.isArray(row.rows) || row.rows.length !== Math.min(request.pageSize, Math.max(0, row.totalCount - (request.page - 1) * request.pageSize))) v.fail(); const counts = ownerCounts(row.ownerCounts); if (row.totalCount > counts[kind]) v.fail(); const rows = row.rows.map(parser); rows.forEach(item => relationCounts(item, counts)); if (new Set(rows.map(item => item.id.toLowerCase())).size !== rows.length) v.fail(); return { rows, page: row.page as number, pageSize: row.pageSize as 10 | 15 | 20, totalCount: row.totalCount as number, baseRevision: row.baseRevision, ownerCounts: counts }; }
function detail<T extends { id: string }>(value: unknown, id: string, parser: (row: unknown) => T, kind: OwnerKind): OwnerSettingsDetail<T> { const result = exact(value, ["row", "baseRevision", "ownerCounts"]); if (typeof result.baseRevision !== "string" || !/^[0-9a-f]{64}$/.test(result.baseRevision)) v.fail(); const counts = ownerCounts(result.ownerCounts); const row = result.row === null ? null : parser(result.row); if (row) relationCounts(row, counts); if (row && (row.id.toLowerCase() !== id.toLowerCase() || counts[kind] < 1)) v.fail(); return { row, baseRevision: result.baseRevision, ownerCounts: counts }; }
export function listTextbookPublisherPage(request: SettingPageRequest, options: TextbookReadOptions = {}) { pageRequest(request); const deadline = AbortSignal.timeout(8000); const signal = options.signal ? AbortSignal.any([options.signal, deadline]) : deadline; return readTextbookPurpose({ ...options, signal }, client => client.rpc("list_textbook_publisher_page_v1", { p_filters: request.filters, p_draft: request.draft, p_sort: request.sort, p_page: request.page, p_page_size: request.pageSize }).abortSignal(signal).retry(false), data => page(data, request, publisher, "publishers")); }
export function listTextbookSupplierPage(request: SettingPageRequest, options: TextbookReadOptions = {}) { pageRequest(request); const deadline = AbortSignal.timeout(8000); const signal = options.signal ? AbortSignal.any([options.signal, deadline]) : deadline; return readTextbookPurpose({ ...options, signal }, client => client.rpc("list_textbook_supplier_page_v1", { p_filters: request.filters, p_draft: request.draft, p_sort: request.sort, p_page: request.page, p_page_size: request.pageSize }).abortSignal(signal).retry(false), data => page(data, request, supplier, "suppliers")); }
export function listTextbookSupplierSettingPickerPage(request: SettingPageRequest, options: TextbookReadOptions = {}) { pageRequest(request); const deadline = AbortSignal.timeout(8000); const signal = options.signal ? AbortSignal.any([options.signal, deadline]) : deadline; return readTextbookPurpose({ ...options, signal }, client => client.rpc("list_textbook_supplier_setting_picker_page_v1", { p_filters: request.filters, p_draft: request.draft, p_sort: request.sort, p_page: request.page, p_page_size: request.pageSize }).abortSignal(signal).retry(false), data => page(data, request, option, "suppliers")); }
function detailInput(input: unknown): asserts input is { id: string; draft: import("./textbook-settings-types").OwnerDraft | null } { if (!object(input) || Object.keys(input).length !== 2 || !v.uuid(input.id)) v.fail("input"); if (input.draft !== null) assertOwnerDraft(input.draft); }
export function getTextbookPublisherSettingDetail(input: { id: string; draft: import("./textbook-settings-types").OwnerDraft | null }, options: TextbookReadOptions = {}) { detailInput(input); const deadline = AbortSignal.timeout(8000); const signal = options.signal ? AbortSignal.any([options.signal, deadline]) : deadline; return readTextbookPurpose({ ...options, signal }, client => client.rpc("get_textbook_publisher_setting_detail_v1", { p_id: input.id, p_draft: input.draft }).abortSignal(signal).retry(false), data => detail(data, input.id, publisher, "publishers")); }
export function getTextbookSupplierSettingDetail(input: { id: string; draft: import("./textbook-settings-types").OwnerDraft | null }, options: TextbookReadOptions = {}) { detailInput(input); const deadline = AbortSignal.timeout(8000); const signal = options.signal ? AbortSignal.any([options.signal, deadline]) : deadline; return readTextbookPurpose({ ...options, signal }, client => client.rpc("get_textbook_supplier_setting_detail_v1", { p_id: input.id, p_draft: input.draft }).abortSignal(signal).retry(false), data => detail(data, input.id, supplier, "suppliers")); }
