import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { test } from 'node:test';
import { createAgentApiHandler } from '../src/features/agent-api/server/http.ts';
const token = 'tips_agent_'+'a'.repeat(64);
const id='a1290000-0000-4000-8000-000000000001';
const key='a1290000-0000-4000-8000-000000000002';
function harness(result={data:{data:{ok:true}},error:null},enabled=true) {
 const calls=[];return {calls,run:createAgentApiHandler({enabled:()=>enabled,rpc:async (...args)=>{calls.push(args);return result;}})};}
function req(path,{method='GET',body,headers={},auth=true}={}) {return new Request('https://tips.test/api/v1/'+path,{method,headers:{...(auth?{authorization:'Bearer '+token}:{}),...(body!==undefined?{'content-type':'application/json'}:{}),...headers},body:body===undefined?undefined:typeof body==='string'?body:JSON.stringify(body)});}
const input={expectedVersion:'b'.repeat(64),slotId:'live:class:slot',startMinute:600,endMinute:660,reason:'requested weekly adjustment'};
test('closed by default and rejects anonymous before database access',async()=>{for(const [enabled,auth,status] of [[false,true,503],[true,false,401]]){const h=harness(undefined,enabled);assert.equal((await h.run(req('health',{auth}),['health'])).status,status);assert.equal(h.calls.length,0)}});
test('forwards only a digest and server-selected operation',async()=>{const h=harness();const res=await h.run(req('classes?search=A&page=2'),['classes']);assert.equal(res.status,200);assert.equal(res.headers.get('cache-control'),'no-store');assert.deepEqual(h.calls[0],['agent_api_v1',{p_token_hash:createHash('sha256').update(token).digest('hex'),p_action:'classes',p_input:{search:'A',page:2}}]);assert.ok(!JSON.stringify(h.calls).includes(token))});
test('ambiguous/unsupported inputs never reach domain writes',async()=>{const cases=[['classes?page=1&page=2',['classes'],{}],['classes?studentIds=true',['classes'],{}],['classes/not-uuid',['classes','not-uuid'],{}],['operations',['operations'],{method:'POST',body:{previewToken:id}}],['classes/'+id+'/weekly-time/preview',['classes',id,'weekly-time','preview'],{method:'POST',body:{...input,startMinute:700}}],['classes/'+id+'/weekly-time/preview',['classes',id,'weekly-time','preview'],{method:'POST',body:{...input,studentIds:[]}}]];for(const [path,parts,options] of cases){const h=harness();assert.equal((await h.run(req(path,options),parts)).status,400);assert.equal(h.calls.length,0)}});
test('preview has exact target and no arbitrary mutation parameters',async()=>{const h=harness();assert.equal((await h.run(req('classes/'+id+'/weekly-time/preview',{method:'POST',body:input}),['classes',id,'weekly-time','preview'])).status,200);assert.equal(h.calls[0][1].p_action,'preview');assert.deepEqual(h.calls[0][1].p_input,{...input,classId:id})});
test('known failed commit returns durable receipt, and GET status remains readable',async()=>{const receipt={operationId:key,state:'failed',error:{code:'timetable_resource_conflict',sqlstate:'23P01'}};const h=harness({data:{data:receipt},error:null});const res=await h.run(req('operations',{method:'POST',body:{previewToken:id},headers:{'Idempotency-Key':key}}),['operations']);assert.equal(res.status,409);assert.deepEqual((await res.json()).data,receipt);assert.equal((await h.run(req('operations/'+key),['operations',key])).status,200)});
test('unknown operation is never manufactured into failure or success',async()=>{const h=harness({data:{data:{operationId:key,state:'unknown',retryWithNewKey:false}},error:null});const res=await h.run(req('operations/'+key),['operations',key]);assert.equal((await res.json()).data.state,'unknown')});
test('sanitizes raw SQL errors and supplies typed rate/auth errors',async()=>{const h=harness({data:null,error:{message:'password=do-not-print secret',code:'XX000'}});const res=await h.run(req('health'),['health']);assert.equal(res.status,503);assert.ok(!(await res.text()).includes('do-not-print'));const rate=harness({data:{error:{code:'agent_rate_limited'}},error:null});const rr=await rate.run(req('health'),['health']);assert.equal(rr.status,429);assert.equal(rr.headers.get('retry-after'),'60')});
test('bounds streaming bodies and requires JSON',async()=>{for(const [body,headers,status] of [['x'.repeat(9000),{},413],['{',{},400],['{}',{'content-type':'text/plain'},415]]){const h=harness();const res=await h.run(req('operations',{method:'POST',body,headers:{'Idempotency-Key':key,...headers}}),['operations']);assert.equal(res.status,status);assert.equal(h.calls.length,0)}});
test('public schema has stable operations without revealing credentials',async()=>{const h=harness(undefined,false);const r=await h.run(req('openapi',{auth:false}),['openapi']);assert.equal(r.status,200);const spec=await r.json();assert.equal(spec.openapi,'3.1.0');assert.equal(Object.keys(spec.paths).length,7);assert.equal(h.calls.length,0)});
