import assert from "node:assert/strict"
import test from "node:test"
import { openFilter, chooseFilter, closeFilter } from "./helpers/textbook-filter-actions.mjs"

import { purchaseRow, purchaseSummary, saleRow, saleSummary, setup } from "./helpers/textbook-numbered-harness.mjs"

// Keep Radix filter interactions in a fresh DOM process, independent of the large renderer fixture suite.
const preparedRowIds = (surface) => [...document.querySelectorAll(`[data-prepared-surface="${surface}"]`)]
  .map((node) => node.getAttribute("data-prepared-row-id"))

test('sale filters keep search, controls and accepted rows mounted through pending and empty results', async (t) => {
  const h = await setup(t, { search: '?textbookTab=sales' })
  await h.resolve(h.requests.find(r => r.name === 'list_textbook_sale_page_v1'), { rows: [saleRow()], page: 1, pageSize: 10, totalCount: 1 })
  await h.resolve(h.requests.find(r => r.name === 'get_textbook_sale_summary_v1'), saleSummary())
  const search = document.querySelector('[aria-label="출고 검색"][type="search"]')
  const filter = document.querySelector('[aria-label="출고 상태"]')
  const add = document.querySelector('[aria-label="교재 출고 추가"]')
  const rows = preparedRowIds('sales-process-desktop')
  assert.equal(rows.length, 1)
  await chooseFilter(h, '출고 상태', '출고 완료')
  const pending = h.requests.filter(r => r.name === 'list_textbook_sale_page_v1').at(-1)
  assert.equal(pending.args.p_filters.status, 'issued')
  assert.deepEqual(preparedRowIds('sales-process-desktop'), rows, 'accepted rows remain until the replacement arrives')
  assert.equal(document.querySelector('[aria-label="출고 상태"]'), filter)
  assert.equal(filter.textContent, '출고 완료')
  await h.resolve(pending, { rows: [], page: 1, pageSize: 10, totalCount: 0 })
  await h.resolve(h.requests.filter(r => r.name === 'get_textbook_sale_summary_v1').at(-1), { ...saleSummary(0), classCount: 0, groups: [] })
  assert.equal(document.querySelector('[aria-label="출고 검색"][type="search"]'), search)
  assert.equal(document.querySelector('[aria-label="교재 출고 추가"]'), add)
  assert.equal(document.querySelector('[aria-label="출고 상태"]'), filter)
  assert.equal(document.querySelector('[aria-label="메이크에듀 청구 준비 열기"]').disabled, true)
  assert.equal(preparedRowIds('sales-process-desktop').length, 0)
  const finalOptions = (await openFilter(h, '출고 상태')).map(node => node.textContent)
  assert.ok(finalOptions.includes('반품0'), JSON.stringify(finalOptions))
  await closeFilter(h)
  assert.equal(document.activeElement, filter)
  await h.assertNoLegacyReads()
})

test('purchase filter options stay complete during rapid changes and failed reads', async (t) => {
  const h = await setup(t, { search: '?textbookTab=purchase' })
  await h.resolve(h.requests.find(r => r.name === 'list_textbook_purchase_page_v1'), { rows: [purchaseRow('order')], page: 1, pageSize: 10, totalCount: 1 })
  await h.resolve(h.requests.find(r => r.name === 'get_textbook_purchase_summary_v1'), purchaseSummary('order'))
  const search = document.querySelector('[aria-label="주문·입고 검색"][type="search"]')
  const stage = document.querySelector('[aria-label="주문·입고 단계"]')
  const rows = preparedRowIds('purchase-desktop')
  assert.equal(rows.length, 1)
  const options = await openFilter(h, '주문·입고 단계')
  assert.equal(options.length, 5, 'zero-result options are retained')
  await closeFilter(h)
  await chooseFilter(h, '주문·입고 단계', '부분입고')
  const obsolete = h.requests.filter(r => r.name === 'list_textbook_purchase_page_v1').at(-1)
  assert.deepEqual(preparedRowIds('purchase-desktop'), rows)
  await chooseFilter(h, '주문·입고 단계', '반품 완료')
  const latest = h.requests.filter(r => r.name === 'list_textbook_purchase_page_v1').at(-1)
  assert.equal(latest.args.p_filters.orderFilter, 'returned')
  assert.equal(obsolete.signal.aborted, true)
  await h.resolve(obsolete, { rows: [], page: 1, pageSize: 10, totalCount: 0 })
  assert.deepEqual(preparedRowIds('purchase-desktop'), rows)
  await h.reject(latest, { message: '합성 조회 실패' })
  assert.equal(document.querySelector('[aria-label="주문·입고 단계"]'), stage)
  assert.equal(document.querySelector('[aria-label="주문·입고 검색"][type="search"]'), search)
  assert.equal(stage.textContent, '반품 완료')
  assert.deepEqual(preparedRowIds('purchase-desktop'), rows)
  const readFeedback = document.querySelector('[data-slot="data-table-toolbar"] [role="alert"]')
  assert.ok(readFeedback, document.body.textContent)
  assert.ok(readFeedback.textContent.includes('목록 조회 실패'))
  assert.ok(readFeedback.textContent.includes('처리 중 오류가 발생했습니다. 잠시 후 다시 시도하세요.'))
  assert.equal(readFeedback.textContent.includes('합성 조회 실패'), false)
  assert.ok(readFeedback.querySelector('[aria-label="교재 목록 다시 시도"]'))
  assert.equal(document.querySelector('[aria-label="주문 문서 메뉴"]'), null, 'read feedback replaces list actions until the read recovers')
  assert.equal(h.requests.some(r => r.table), false)
  const requestCount = h.requests.filter(r => r.name === 'list_textbook_purchase_page_v1').length
  await h.act(() => document.querySelector('[aria-label="주문·입고 필터 초기화"]').click())
  const resetReads = h.requests.filter(r => r.name === 'list_textbook_purchase_page_v1')
  assert.equal(resetReads.length, requestCount + 1, 'reset is one batched page read')
  assert.deepEqual(resetReads.at(-1).args.p_filters, { search: '', mode: 'order', boardScope: 'active', requestFilter: 'all', orderFilter: 'all' })
  assert.equal(document.querySelector('[aria-label="주문·입고 필터 초기화"]').disabled, true)
  await h.assertNoLegacyReads()
})
