/* eslint-disable @typescript-eslint/no-explicit-any */
import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createElement, StrictMode, useEffect, useMemo, act } from 'react';
import { createRoot } from 'react-dom/client';
// @ts-expect-error jsdom is installed for tests without its optional declaration package.
import { JSDOM } from 'jsdom';
import { createTimetablePlanController } from '../src/features/academic/timetable-plan-model.ts';
import { useTimetablePlanSession } from '../src/features/academic/use-timetable-plan-session.ts';

const item = { id:'item',planId:'plan',revision:1,name:'Math',subject:'math',subjectAreaKey:null,grade:'1',capacity:null,tuition:null,defaultTeacherId:null,defaultClassroomId:null,durationMinutes:null,sourceClassId:null,state:'draft' as const,appliedClassId:null,appliedTransferId:null,appliedAt:null,pendingSlots:[] };
const slot = {id:'slot',itemId:'item',planId:'plan',weekday:1,startMinute:600,endMinute:650,teacherId:'teacher',classroomId:'room',sourceSlotId:null};
const snapshot = () => ({plan:{id:'plan',name:'A',state:'draft' as const,metaRevision:1,changeSequence:1,targetStartDate:null,targetEndDate:null},items:[item],slots:[slot],appliedSnapshots:[],members:[],permissions:{canManage:false,canEdit:true,canTransfer:false},capacity:{itemCount:1,slotCount:1,maxItems:500 as const,maxSlots:2000 as const,exceeded:false},asOfDate:'2026-09-23',shadowSlots:[],shadowClasses:[],catalogs:{teachers:[],classrooms:[]},unresolvedOccupancies:[],shadowFingerprint:'fingerprint',datedSessions:[],datedUnresolvedOccupancies:[],datedFingerprint:'dated',datedComplete:true,complete:true});

test('actual React StrictMode effect replay retains a live controller that loads and saves',async()=>{const dom=new JSDOM('<div id="root"></div>',{url:'http://localhost/'});const previous={window:globalThis.window,document:globalThis.document,sessionStorage:globalThis.sessionStorage,IS_REACT_ACT_ENVIRONMENT:(globalThis as any).IS_REACT_ACT_ENVIRONMENT};Object.assign(globalThis,{window:dom.window,document:dom.window.document,sessionStorage:dom.window.sessionStorage,IS_REACT_ACT_ENVIRONMENT:true});let saves=0;let exposed:any;const service={readPlan:async()=>snapshot(),readRevision:async()=>({planId:'plan',metaRevision:1,changeSequence:1,shadowFingerprint:'fingerprint',complete:true}),saveItem:async()=>{saves++;return {planId:'plan',metaRevision:1,changeSequence:2,shadowFingerprint:'fingerprint',item:{...item,revision:2},slots:[{...slot,startMinute:610,endMinute:660}],removedItemIds:[]}}};function Harness(){const controller=useMemo(()=>createTimetablePlanController({service,actorScope:'actor',planId:'plan'}),[]);const state=useTimetablePlanSession({controller,actorScope:'actor',planId:'plan',signalClient:null});useEffect(()=>{exposed={state,controller}},[controller,state]);return createElement('div',null,state.snapshot?.plan.name??'none');}const root=createRoot(dom.window.document.getElementById('root')!);try{await act(async()=>{root.render(createElement(StrictMode,null,createElement(Harness)))});assert.equal(dom.window.document.getElementById('root')?.textContent,'A');await act(async()=>{await exposed.controller.dispatch({operation:'save',item,slots:[{...slot,startMinute:610,endMinute:660}]})});assert.equal(saves,1);assert.equal(exposed.state.snapshot?.slots[0].startMinute,610);}finally{await act(async()=>root.unmount());Object.assign(globalThis,previous);dom.window.close();}});
test('actor cleanup removes recovery for unmounted plans while keeping another actor',async()=>{const {clearTimetableActorRecovery,timetableDraftStorageKey}=await import('../src/features/academic/timetable-plan-recovery.ts');const dom=new JSDOM('',{url:'http://localhost/'});const store=dom.window.sessionStorage;const p1=timetableDraftStorageKey('actor','p1'),p2=timetableDraftStorageKey('actor','p2'),other=timetableDraftStorageKey('other','p1');store.setItem(p1,'draft 1');store.setItem(p2,'draft 2');store.setItem(other,'other');clearTimetableActorRecovery('actor',store);assert.equal(store.getItem(p1),null);assert.equal(store.getItem(p2),null);assert.equal(store.getItem(other),'other');dom.window.close();});
test('actual plan switch keeps same-actor drafts through child unmount for provider logout cleanup',async()=>{const {clearTimetableActorRecovery,timetableDraftStorageKey}=await import('../src/features/academic/timetable-plan-recovery.ts');const dom=new JSDOM('<div id="root"></div>',{url:'http://localhost/'});const previous={window:globalThis.window,document:globalThis.document,sessionStorage:globalThis.sessionStorage,IS_REACT_ACT_ENVIRONMENT:(globalThis as any).IS_REACT_ACT_ENVIRONMENT};Object.assign(globalThis,{window:dom.window,document:dom.window.document,sessionStorage:dom.window.sessionStorage,IS_REACT_ACT_ENVIRONMENT:true});let active:any;const service={readPlan:async(planId:string)=>{const base=snapshot();return {...base,plan:{...base.plan,id:planId},items:[{...item,planId}],slots:[{...slot,planId}]}},readRevision:async()=>({planId:'plan',metaRevision:1,changeSequence:1,shadowFingerprint:'fingerprint',complete:true}),saveItem:async()=>new Promise<never>(()=>{})};function Harness({planId}:{planId:string}){const controller=useMemo(()=>createTimetablePlanController({service,actorScope:'actor',planId}),[planId]);useTimetablePlanSession({controller,actorScope:'actor',planId,signalClient:null});useEffect(()=>{active=controller},[controller]);return createElement('div',null,planId)}const root=createRoot(dom.window.document.getElementById('root')!);try{await act(async()=>root.render(createElement(Harness,{planId:'p1'})));await act(async()=>{void active.dispatch({operation:'save',item:{...item,planId:'p1'},slots:[{...slot,planId:'p1'}]})});const p1=timetableDraftStorageKey('actor','p1'),p2=timetableDraftStorageKey('actor','p2');assert.ok(dom.window.sessionStorage.getItem(p1));await act(async()=>root.render(createElement(Harness,{planId:'p2'})));assert.ok(dom.window.sessionStorage.getItem(p1));await act(async()=>{void active.dispatch({operation:'save',item:{...item,planId:'p2'},slots:[{...slot,planId:'p2'}]})});assert.ok(dom.window.sessionStorage.getItem(p2));assert.ok(dom.window.sessionStorage.getItem(p1));assert.ok(dom.window.sessionStorage.getItem(p2));await act(async()=>{clearTimetableActorRecovery('actor',dom.window.sessionStorage)});await assert.rejects(active.dispatch({operation:'save',item:{...item,planId:'p2'},slots:[{...slot,planId:'p2'}]}),/timetable_plan_inactive/);assert.throws(()=>active.resume(),/timetable_plan_inactive/);await act(async()=>root.unmount());assert.equal(dom.window.sessionStorage.getItem(p1),null);assert.equal(dom.window.sessionStorage.getItem(p2),null);}finally{Object.assign(globalThis,previous);dom.window.close();}});
