/* eslint-disable @typescript-eslint/no-explicit-any */
import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createTimetablePlanController } from '../src/features/academic/timetable-plan-model.ts';

function deferred<T>() { let resolve!: (value:T)=>void; let reject!: (reason:unknown)=>void; const promise = new Promise<T>((a,b)=>{resolve=a;reject=b}); return {promise,resolve,reject}; }
const item = { id:'item',planId:'plan',revision:1,name:'Math',subject:'math',subjectAreaKey:null,grade:'1',capacity:null,tuition:null,defaultTeacherId:null,defaultClassroomId:null,durationMinutes:null,sourceClassId:null,state:'draft' as const,appliedClassId:null,appliedTransferId:null,appliedAt:null,pendingSlots:[] };
const slot = { id:'slot',itemId:'item',planId:'plan',weekday:1,startMinute:600,endMinute:650,teacherId:'teacher',classroomId:'room',sourceSlotId:null };
function snapshot(changeSequence=1) { return {plan:{id:'plan',name:'A',state:'draft' as const,metaRevision:1,changeSequence,targetStartDate:null,targetEndDate:null},items:[{...item}],slots:[{...slot}],appliedSnapshots:[],members:[],permissions:{canManage:false,canEdit:true,canTransfer:false},capacity:{itemCount:1,slotCount:1,maxItems:500 as const,maxSlots:2000 as const,exceeded:false},asOfDate:'2026-09-23',shadowSlots:[],shadowClasses:[],catalogs:{teachers:[],classrooms:[]},unresolvedOccupancies:[],shadowFingerprint:'fingerprint',datedSessions:[],datedUnresolvedOccupancies:[],datedFingerprint:'dated',datedComplete:true,complete:true}; }
function result(revision:number,startMinute:number,seq:number) { return {planId:'plan',metaRevision:1,changeSequence:seq,shadowFingerprint:'fingerprint',item:{...item,revision},slots:[{...slot,startMinute,endMinute:startMinute+50}],removedItemIds:[]}; }
function makeService() { const calls:any[]=[]; const pending:any[]=[]; let server=snapshot(); return {calls,pending,setServer:(s:any)=>server=s, service:{readPlan:async()=>structuredClone(server),readRevision:async()=>({planId:'plan',metaRevision:server.plan.metaRevision,changeSequence:server.plan.changeSequence,shadowFingerprint:server.shadowFingerprint,complete:true}),saveItem:(command:any)=>{calls.push(structuredClone(command));const d=deferred<any>();pending.push(d);return d.promise;},mutatePlan:async()=>{throw Error('unused')},previewTransfer:async()=>{throw Error('unused')},commitTransfer:async()=>{throw Error('unused')}}}; }
function edit(startMinute:number) { return {operation:'save' as const,item:{...item},slots:[{...slot,startMinute,endMinute:startMinute+50}]}; }
const memoryStorage=()=>{const values=new Map<string,string>();return {getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value)},removeItem:(key:string)=>{values.delete(key)},keys:()=>[...values.keys()]};};

test('serializes two edits, retains newer intent across reverse responses and uses latest item revision',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const first=c.dispatch(edit(610));const second=c.dispatch(edit(620));assert.equal(h.calls.length,1);assert.equal('revision' in h.calls[0].item,false);assert.equal('state' in h.calls[0].item,false);assert.equal(c.snapshot().draft?.slots[0].startMinute,620);h.pending[0].resolve(result(2,610,2));await first;assert.equal(h.calls.length,2);assert.equal(h.calls[1].expectedItemRevision,2);h.pending[1].resolve(result(3,620,3));await second;assert.equal(c.snapshot().draft?.slots[0].startMinute,620);assert.equal(c.snapshot().snapshot?.items[0].revision,3);c.destroy();});
test('ambiguous failure retries immutable request while newer draft stays queued',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const first=c.dispatch(edit(610));const second=c.dispatch(edit(620));const submitted=structuredClone(h.calls[0]);h.pending[0].reject(Error('network'));await assert.rejects(first);assert.equal(c.snapshot().saveState,'error');assert.equal(c.snapshot().draft?.slots[0].startMinute,620);const retry=c.retry();assert.deepEqual(h.calls[1],submitted);h.pending[1].resolve(result(2,610,2));await retry;assert.equal(h.calls[2].expectedItemRevision,2);h.pending[2].resolve(result(3,620,3));await second;c.destroy();});
test('refresh preserves local draft and stale shows latest server',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const save=c.dispatch(edit(620));h.setServer({...snapshot(2),items:[{...item,revision:2}],slots:[{...slot,startMinute:640,endMinute:690}]});await c.refresh();assert.equal(c.snapshot().snapshot?.slots[0].startMinute,640);assert.equal(c.snapshot().draft?.slots[0].startMinute,620);assert.equal(c.snapshot().saveState,'stale');h.pending[0].resolve(result(2,620,2));await assert.rejects(save,/timetable_stale/);assert.equal(c.snapshot().snapshot?.items[0].revision,2);c.destroy();});
test('reload recovers submitted identity; actor or plan switch never exposes previous draft',async()=>{const store=memoryStorage();const h=makeService();const a=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:store});await a.load();void a.dispatch(edit(620));const sent=structuredClone(h.calls[0]);a.destroy();const b=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:store});await b.load();assert.equal(b.snapshot().draft?.slots[0].startMinute,620);const retry=b.retry();assert.deepEqual(h.calls[1],sent);h.pending[1].resolve(result(2,620,2));await retry;const other=createTimetablePlanController({service:h.service,actorScope:'other',planId:'plan',storage:store});assert.equal(other.snapshot().draft,null);const plan2=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan2',storage:store});assert.equal(plan2.snapshot().draft,null);b.destroy();other.destroy();plan2.destroy();});
test('receipt replay cannot lower a newer snapshot item or restore old coordinates',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const save=c.dispatch(edit(610));h.setServer({...snapshot(3),items:[{...item,revision:3}],slots:[{...slot,startMinute:660,endMinute:710}]});await c.refresh();h.pending[0].resolve(result(2,610,2));await assert.rejects(save,/timetable_stale/);assert.equal(c.snapshot().snapshot?.items[0].revision,3);assert.equal(c.snapshot().snapshot?.slots[0].startMinute,660);c.destroy();});
test('poll compares composite fingerprint even without plan sequence change',async()=>{const h=makeService();let server=snapshot();h.service.readRevision=async()=>({planId:'plan',metaRevision:1,changeSequence:1,shadowFingerprint:'next-kst-day',complete:true});h.service.readPlan=async()=>structuredClone(server);const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();server={...snapshot(),shadowFingerprint:'next-kst-day',asOfDate:'2026-09-24'};await c.checkRevision();assert.equal(c.snapshot().snapshot?.asOfDate,'2026-09-24');c.destroy();});
test('transient reference failure preserves prior display but blocks another save',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();h.service.readPlan=async()=>{throw Error('network')};await c.refresh();assert.equal(c.snapshot().snapshot?.slots[0].startMinute,600);assert.equal(c.snapshot().referenceStatus,'unverifiable');await assert.rejects(c.dispatch(edit(630)),/timetable_reference_unverifiable/);assert.equal(h.calls.length,0);assert.equal(c.snapshot().draft?.slots[0].startMinute,630);c.destroy();});
test('permission revocation clears scoped snapshot and same-tab recovery',async()=>{const store=memoryStorage();const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:store});await c.load();void c.dispatch(edit(630));assert.equal(store.keys().length,1);h.service.readPlan=async()=>{throw {code:'42501',message:'timetable_forbidden'}};await c.refresh();assert.equal(c.snapshot().snapshot,null);assert.equal(c.snapshot().draft,null);assert.equal(store.keys().length,0);c.destroy();});
test('undo is a new revision-checked inverse command',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const first=c.dispatch(edit(620));h.pending[0].resolve(result(2,620,2));await first;const undo=c.undo();assert.equal(h.calls[1].expectedItemRevision,2);assert.equal(h.calls[1].slots[0].startMinute,600);assert.notEqual(h.calls[1].requestKey,h.calls[0].requestKey);h.pending[1].resolve(result(3,600,3));await undo;assert.equal(c.snapshot().snapshot?.slots[0].startMinute,600);c.destroy();});
test('undo refuses to rebase across a collaborator edit of the same item',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const first=c.dispatch(edit(620));h.pending[0].resolve(result(2,620,2));await first;h.setServer({...snapshot(3),items:[{...item,revision:3}],slots:[{...slot,startMinute:640,endMinute:690}]});await c.refresh();await assert.rejects(c.undo(),/timetable_stale/);assert.equal(h.calls.length,1);assert.equal(c.snapshot().snapshot?.slots[0].startMinute,640);assert.equal(c.snapshot().draft?.slots[0].startMinute,600);c.destroy();});
test('item A stale does not stop independent item B save',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const a=c.dispatch(edit(610));h.pending[0].reject({code:'P0001',message:'timetable_stale'});await assert.rejects(a);const bItem={...item,id:'item-b'};const bSlot={...slot,id:'slot-b',itemId:'item-b',startMinute:700,endMinute:750};const b=c.dispatch({operation:'save',item:bItem,slots:[bSlot]});assert.equal(h.calls.length,2);assert.equal(h.calls[1].item.id,'item-b');h.pending[1].resolve({...result(1,700,2),item:{...bItem,revision:1},slots:[bSlot]});await b;assert.equal(c.snapshot().saveState,'stale');c.destroy();});
test('explicit reapply uses latest revision and a new request key while retaining the local draft',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const first=c.dispatch(edit(620));h.pending[0].reject({code:'P0001',message:'timetable_stale'});await assert.rejects(first);h.setServer({...snapshot(2),items:[{...item,revision:2}],slots:[{...slot,startMinute:640,endMinute:690}]});await c.refresh();assert.equal(c.snapshot().draft?.slots[0].startMinute,620);const reapplied=c.resolveStale('item','reapply_draft');assert.equal(h.calls.length,2);assert.equal(h.calls[1].expectedItemRevision,2);assert.notEqual(h.calls[1].requestKey,h.calls[0].requestKey);assert.equal(h.calls[1].slots[0].startMinute,620);h.pending[1].resolve(result(3,620,3));await reapplied;c.destroy();});
test('accept-server drops only the conflicted item draft',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const first=c.dispatch(edit(620));h.pending[0].reject({code:'P0001',message:'timetable_stale'});await assert.rejects(first);h.setServer({...snapshot(2),items:[{...item,revision:2}],slots:[{...slot,startMinute:640,endMinute:690}]});await c.refresh();await c.resolveStale('item','accept_server');assert.equal(c.snapshot().draft?.slots[0].startMinute,640);assert.equal(c.snapshot().dirty,false);c.destroy();});
test('late read and save permission failures from a retired epoch leave newly loaded state alone',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const saved=c.dispatch(edit(610));const lateRead=deferred<any>();h.service.readPlan=()=>lateRead.promise;const refreshing=c.refresh();c.clearSensitive();h.service.readPlan=async()=>snapshot();await c.load();h.pending[0].reject({code:'42501',message:'timetable_forbidden'});lateRead.reject({code:'42501',message:'timetable_forbidden'});await refreshing;await Promise.resolve();assert.equal(c.snapshot().snapshot?.plan.id,'plan');assert.equal(c.snapshot().referenceStatus,'verified');c.destroy();void saved.catch(()=>{});});
test('transfer delta applies source state and class labels atomically',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const original=snapshot();const shadow={id:'live:class:slot',classId:'class',sourceSlotId:'slot',weekday:1,startMinute:600,endMinute:650,teacherId:'teacher',classroomId:'room',classRevision:1};const reference={asOfDate:original.asOfDate,shadowSlots:[shadow],shadowClasses:[{id:'class',name:'New Class',subject:'math',grade:'1',status:'수강' as const,revision:1}],catalogs:original.catalogs,unresolvedOccupancies:[],shadowFingerprint:'next',datedSessions:[],datedUnresolvedOccupancies:[],datedFingerprint:'dated-next',datedComplete:true,complete:true};c.applyTransfer({transferId:'transfer',shadowFingerprint:'next',mappings:[],appliedItems:[{...item,state:'applied',revision:2,appliedClassId:'class',appliedTransferId:'transfer',appliedAt:'2026-09-23T00:00:00Z'}],removedItemIds:[],addedShadowSlots:[shadow],addedShadowClasses:reference.shadowClasses,createdItems:[],createdSlots:[],sourcePlan:{...original.plan,changeSequence:2},operatingReference:reference});assert.equal(c.snapshot().snapshot?.shadowClasses[0].name,'New Class');assert.equal(c.snapshot().snapshot?.items[0].state,'applied');assert.equal(c.snapshot().snapshot?.slots.length,0);assert.equal(c.snapshot().snapshot?.appliedSnapshots[0].slots[0].id,'slot');c.destroy();});
test('ambiguous save visible in refresh still replays original receipt key and body',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const first=c.dispatch(edit(620));const submitted=structuredClone(h.calls[0]);h.pending[0].reject(Error('network'));await assert.rejects(first);h.setServer({...snapshot(2),items:[{...item,revision:2}],slots:[{...slot,startMinute:620,endMinute:670}]});await c.refresh();const retried=c.retry('item');assert.deepEqual(h.calls[1],submitted);h.pending[1].resolve(result(2,620,2));await retried;assert.equal(c.snapshot().draft?.slots[0].startMinute,620);assert.equal(c.snapshot().dirty,false);c.destroy();});
test('replayed old receipt cannot auto-send newer queued intent over collaborator revision',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const first=c.dispatch(edit(610));void c.dispatch(edit(620)).catch(()=>{});h.pending[0].reject(Error('network'));await assert.rejects(first);h.setServer({...snapshot(3),items:[{...item,revision:3}],slots:[{...slot,startMinute:650,endMinute:700}]});await c.refresh();const retried=c.retry('item');h.pending[1].resolve(result(2,610,2));await assert.rejects(retried,/timetable_stale/);assert.equal(h.calls.length,2);assert.equal(c.snapshot().snapshot?.items[0].revision,3);assert.equal(c.snapshot().draft?.slots[0].startMinute,620);assert.equal(c.snapshot().saveState,'stale');c.destroy();});
test('late successful read from retired epoch cannot reopen old scope data',async()=>{const h=makeService();const first=deferred<any>();let reads=0;h.service.readPlan=async()=>++reads===1?first.promise:snapshot();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});const loading=c.load();c.clearSensitive();await c.load();first.resolve({...snapshot(99),plan:{...snapshot(99).plan,name:'Old reply',changeSequence:99}});await loading;assert.equal(c.snapshot().snapshot?.plan.name,'A');c.destroy();});
test('older successful receipt cannot resurrect an item deleted in newer authoritative snapshot',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const saving=c.dispatch(edit(610));h.setServer({...snapshot(3),items:[],slots:[]});await c.refresh();h.pending[0].resolve(result(2,610,2));await assert.rejects(saving,/timetable_stale/);assert.equal(c.snapshot().snapshot?.items.length,0);assert.equal(c.snapshot().snapshot?.slots.length,0);assert.equal(c.snapshot().draft?.slots[0].startMinute,610);assert.equal(c.snapshot().saveState,'stale');c.destroy();});
test('own-save signal before receipt still drains queued second edit',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const first=c.dispatch(edit(610));const second=c.dispatch(edit(620));h.setServer({...snapshot(2),items:[{...item,revision:2}],slots:[{...slot,startMinute:610,endMinute:660}]});await c.refresh();h.pending[0].resolve(result(2,610,2));await first;assert.equal(h.calls.length,2);assert.equal(h.calls[1].expectedItemRevision,2);h.pending[1].resolve(result(3,620,3));await second;assert.equal(c.snapshot().draft?.slots[0].startMinute,620);c.destroy();});
test('paused retired controller rejects old action references and terminal destroy cannot resume',async()=>{const h=makeService();const store=memoryStorage();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:store});await c.load();c.pause();await assert.rejects(c.dispatch(edit(620)),/timetable_plan_inactive/);await assert.rejects(c.retry(),/timetable_plan_inactive/);await assert.rejects(c.resolveStale('item','reapply_draft'),/timetable_plan_inactive/);await assert.rejects(c.undo(),/timetable_plan_inactive/);assert.equal(h.calls.length,0);assert.equal(store.keys().length,0);c.destroy();assert.throws(()=>c.resume(),/timetable_plan_inactive/);});
test('independent creates merge when later sequence receipt arrives first without a full refresh',async()=>{const h=makeService();const empty={...snapshot(),items:[],slots:[],capacity:{...snapshot().capacity,itemCount:0,slotCount:0}};h.setServer(empty);const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const aItem={...item,id:'a'};const bItem={...item,id:'b'};const aSlot={...slot,id:'a-slot',itemId:'a'};const bSlot={...slot,id:'b-slot',itemId:'b',startMinute:700,endMinute:750};const a=c.dispatch({operation:'save',item:aItem,slots:[aSlot]});const b=c.dispatch({operation:'save',item:bItem,slots:[bSlot]});assert.equal(h.calls.length,2);h.pending[1].resolve({planId:'plan',metaRevision:1,changeSequence:3,shadowFingerprint:'fingerprint',item:{...bItem,revision:1},slots:[bSlot],removedItemIds:[]});await b;h.pending[0].resolve({planId:'plan',metaRevision:1,changeSequence:2,shadowFingerprint:'fingerprint',item:{...aItem,revision:1},slots:[aSlot],removedItemIds:[]});await a;assert.deepEqual(c.snapshot().snapshot?.items.map((entry)=>entry.id).sort(),['a','b']);assert.deepEqual(c.snapshot().snapshot?.slots.map((entry)=>entry.id).sort(),['a-slot','b-slot']);assert.equal(c.snapshot().dirty,false);c.destroy();});
test('malformed applied transfer item cannot strip source slots or mark the view verified',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const original=snapshot();const malformed={id:'item',planId:'other-plan',revision:2,state:'draft',pendingSlots:[]};const reference={asOfDate:original.asOfDate,shadowSlots:[],shadowClasses:[],catalogs:original.catalogs,unresolvedOccupancies:[],shadowFingerprint:'next',datedSessions:[],datedUnresolvedOccupancies:[],datedFingerprint:'dated-next',datedComplete:true,complete:true};assert.throws(()=>c.applyTransfer({transferId:'transfer',shadowFingerprint:'next',mappings:[],appliedItems:[malformed as any],removedItemIds:[],addedShadowSlots:[],addedShadowClasses:[],createdItems:[],createdSlots:[],sourcePlan:{...original.plan,changeSequence:2},operatingReference:reference}),/timetable_plan_response_invalid/);assert.equal(c.snapshot().snapshot?.items[0].planId,'plan');assert.equal(c.snapshot().snapshot?.slots[0].id,'slot');assert.equal(c.snapshot().snapshot?.shadowFingerprint,'fingerprint');c.destroy();});
test('independent delete receipt still applies after a later unrelated create receipt',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const deleting=c.dispatch({operation:'delete',itemId:'item'});const bItem={...item,id:'b'};const bSlot={...slot,id:'b-slot',itemId:'b',startMinute:700,endMinute:750};const creating=c.dispatch({operation:'save',item:bItem,slots:[bSlot]});h.pending[1].resolve({planId:'plan',metaRevision:1,changeSequence:3,shadowFingerprint:'fingerprint',item:{...bItem,revision:1},slots:[bSlot],removedItemIds:[]});await creating;h.pending[0].resolve({planId:'plan',metaRevision:1,changeSequence:2,shadowFingerprint:'fingerprint',item:null,slots:[],removedItemIds:['item']});await deleting;assert.deepEqual(c.snapshot().snapshot?.items.map((entry)=>entry.id),['b']);assert.deepEqual(c.snapshot().snapshot?.slots.map((entry)=>entry.id),['b-slot']);assert.equal(c.snapshot().dirty,false);c.destroy();});
test('complete but unknown applied source item is rejected before a transfer delta merge',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const original=snapshot();const reference={asOfDate:original.asOfDate,shadowSlots:[],shadowClasses:[],catalogs:original.catalogs,unresolvedOccupancies:[],shadowFingerprint:'next',datedSessions:[],datedUnresolvedOccupancies:[],datedFingerprint:'dated-next',datedComplete:true,complete:true};assert.throws(()=>c.applyTransfer({transferId:'transfer',shadowFingerprint:'next',mappings:[],appliedItems:[{...item,id:'missing',revision:2,state:'applied',appliedClassId:null,appliedTransferId:'transfer',appliedAt:'2026-09-23T00:00:00Z'}],removedItemIds:[],addedShadowSlots:[],addedShadowClasses:[],createdItems:[],createdSlots:[],sourcePlan:{...original.plan,changeSequence:2},operatingReference:reference}),/timetable_plan_response_invalid/);assert.equal(c.snapshot().snapshot?.items[0].id,'item');assert.equal(c.snapshot().snapshot?.slots[0].id,'slot');c.destroy();});

for (const failure of [{code:'23P01',message:'timetable_resource_conflict'},{code:'22023',message:'timetable_invalid'}]) test(`confirmed ${failure.code} rejection can be explicitly corrected with a new request identity`,async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const first=c.dispatch(edit(610));h.pending[0].reject(failure);await assert.rejects(first);assert.equal(c.failureKind('item'),'rejected');const correction=c.replaceRejected(edit(620));assert.notEqual(h.calls[1].requestKey,h.calls[0].requestKey);assert.equal(h.calls[1].slots[0].startMinute,620);h.pending[1].resolve(result(2,620,2));await correction;assert.equal(c.snapshot().snapshot?.slots[0].startMinute,620);assert.equal(c.snapshot().dirty,false);c.destroy();});
test('uncertain response cannot be replaced or discarded and retries original immutable body/key',async()=>{for(const failure of [Error('network'),Error('timetable_plan_response_invalid'),{code:'22023',message:'other_error'}]){const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const first=c.dispatch(edit(610));h.pending[0].reject(failure);await assert.rejects(first);assert.equal(c.failureKind('item'),'uncertain');await assert.rejects(c.replaceRejected(edit(620)),/timetable_rejection_required/);await assert.rejects(c.discardRejected('item'),/timetable_rejection_required/);await assert.rejects(c.dispatch(edit(630)),/timetable_failed_edit_pending/);const retry=c.retry('item');assert.deepEqual(h.calls[1],h.calls[0]);h.pending[1].resolve(result(2,610,2));await retry;c.destroy();}});
test('corrected rejected head preserves queued newer edit and independent item draft',async()=>{const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();const first=c.dispatch(edit(610));const newer=c.dispatch(edit(630));const independent=c.dispatch({operation:'save',item:{...item,id:'other'},slots:[]});h.pending[0].reject({code:'23P01',message:'timetable_resource_conflict'});await assert.rejects(first);const correction=c.replaceRejected(edit(620));assert.equal(c.snapshot().draft?.slots.find(s=>s.itemId==='item')?.startMinute,630);assert.ok(c.snapshot().draft?.items.some(i=>i.id==='other'));h.pending[2].resolve(result(2,620,2));await correction;assert.equal(h.calls[3].slots[0].startMinute,630);h.pending[3].resolve(result(3,630,3));await newer;h.pending[1].resolve({planId:'plan',metaRevision:1,changeSequence:4,shadowFingerprint:'fingerprint',item:{...item,id:'other',revision:1},slots:[],removedItemIds:[]});await independent;assert.equal(c.snapshot().snapshot?.slots[0].startMinute,630);assert.equal(c.snapshot().snapshot?.items.length,2);c.destroy();});

test('discard confirmed rejected head advances queued latest edit while preserving independent pending item',async()=>{
 const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();
 const first=c.dispatch(edit(610));const queued=c.dispatch(edit(640));const independent=c.dispatch({operation:'save',item:{...item,id:'other'},slots:[]});
 h.pending[0].reject({code:'23P01',message:'timetable_resource_conflict'});await assert.rejects(first);
 await c.discardRejected('item');assert.equal(h.calls.length,3);assert.equal(h.calls[2].slots[0].startMinute,640);
 assert.equal(c.snapshot().draft?.slots.find(s=>s.itemId==='item')?.startMinute,640);assert.ok(c.snapshot().draft?.items.some(i=>i.id==='other'));
 h.pending[2].resolve(result(2,640,2));await queued;
 h.pending[1].resolve({planId:'plan',metaRevision:1,changeSequence:3,shadowFingerprint:'fingerprint',item:{...item,id:'other',revision:1},slots:[],removedItemIds:[]});await independent;
 assert.equal(c.snapshot().dirty,false);assert.equal(c.snapshot().snapshot?.items.length,2);assert.equal(c.snapshot().snapshot?.slots[0].startMinute,640);c.destroy();
});

test('plan-copy receipt at equal sequence never replaces a newer operating reference or verifies it',async()=>{
 const h=makeService();const c=createTimetablePlanController({service:h.service,actorScope:'actor',planId:'plan',storage:memoryStorage()});await c.load();
 const old=snapshot();
 const newer={...snapshot(),shadowFingerprint:'new-operating',datedFingerprint:'new-dated',datedSessions:[{id:'session',classId:'class',sourceSlotId:null,date:'2026-09-24',state:'active' as const,startMinute:600,endMinute:660,teacherId:'teacher',classroomId:'room',revision:2}]};
 h.setServer(newer);await c.refresh();
 c.applyTransfer({transferId:'copy',shadowFingerprint:old.shadowFingerprint,mappings:[{sourceId:'item',targetId:'target-item',targetClassId:null}],appliedItems:[],removedItemIds:[],addedShadowSlots:[],createdItems:[],createdSlots:[],snapshot:old});
 assert.equal(c.snapshot().snapshot?.shadowFingerprint,'new-operating');assert.equal(c.snapshot().snapshot?.datedFingerprint,'new-dated');
 assert.notEqual(c.snapshot().referenceStatus,'verified');
 await c.refresh();assert.equal(c.snapshot().referenceStatus,'verified');assert.equal(c.snapshot().snapshot?.datedSessions[0].revision,2);c.destroy();
});
