import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createTimetablePlanService } from '../src/features/academic/timetable-plan-service.ts';

const minimalSnapshot={plan:{id:'plan',name:'A',state:'draft',metaRevision:1,changeSequence:1,targetStartDate:null,targetEndDate:null},items:[],slots:[],appliedSnapshots:[],members:[],permissions:{canManage:false,canEdit:true,canTransfer:false},capacity:{itemCount:0,slotCount:0,maxItems:500,maxSlots:2000,exceeded:false},asOfDate:'2026-09-23',shadowSlots:[],shadowClasses:[],catalogs:{teachers:[],classrooms:[]},unresolvedOccupancies:[],shadowFingerprint:'f',datedSessions:[],datedUnresolvedOccupancies:[],datedFingerprint:'d',datedComplete:true,complete:true};
test('uses canonical RPC arguments and forwards AbortSignal',async()=>{const calls=[];const client={rpc(name,args){const call={name,args,signal:null};calls.push(call);return {abortSignal(signal){call.signal=signal;return this},then(resolve){resolve({data:name==='get_timetable_plan_v1'?minimalSnapshot:{planId:'plan',metaRevision:1,changeSequence:1,shadowFingerprint:'f',complete:true},error:null})}}}};const service=createTimetablePlanService({client,actorScope:'actor'});const signal=new AbortController().signal;await service.readPlan('plan',{signal});await service.readRevision('plan',{signal});assert.deepEqual(calls.map(c=>[c.name,c.args]),[['get_timetable_plan_v1',{p_plan_id:'plan'}],['get_timetable_plan_revision_v1',{p_plan_id:'plan'}]]);assert.ok(calls.every(c=>c.signal===signal));});
test('rejects malformed snapshot and never reports synthetic empty success',async()=>{const client={rpc(){return Promise.resolve({data:null,error:null})}};const service=createTimetablePlanService({client,actorScope:'actor'});await assert.rejects(service.readPlan('plan'),/invalid/i);});
test('calls real transfer RPC names and requires atomic label metadata',async()=>{const calls=[];const client={rpc(name,args){calls.push({name,args});return Promise.resolve({data:null,error:{code:'42883',message:'function missing'}})}};const service=createTimetablePlanService({client,actorScope:'actor'});const request={source:{kind:'plan',planId:'plan'},target:{kind:'operational'},mode:'copy',itemIds:['item'],onConflict:'reject'};await assert.rejects(service.previewTransfer(request));assert.equal(calls[0].name,'preview_timetable_plan_transfer_v1');await assert.rejects(service.commitTransfer({request,previewFingerprint:'p',requestKey:'k'}));assert.equal(calls[1].name,'commit_timetable_plan_transfer_v1');});
test('transfer result without labels or complete snapshot fails closed',async()=>{const client={rpc(){return Promise.resolve({data:{transferId:'t',shadowFingerprint:'f',mappings:[],appliedItems:[],removedItemIds:[],addedShadowSlots:[{id:'s'}],createdItems:[],createdSlots:[]},error:null})}};const service=createTimetablePlanService({client,actorScope:'actor'});await assert.rejects(service.commitTransfer({request:{source:{kind:'plan',planId:'p'},target:{kind:'operational'},mode:'copy',itemIds:['i'],onConflict:'reject'},previewFingerprint:'f',requestKey:'k'}),/invalid/i);});
test('minimal signals refresh selected plan or operating shadow; visible poll and focus recover missed events',async()=>{const {watchTimetablePlan}=await import('../src/features/academic/timetable-plan-service.ts');const handlers=[];let subscribed=0,removed=0,pollFn;const docEvents=new Map(),winEvents=new Map();const channel={on(_kind,filter,callback){handlers.push({filter,callback});return this},subscribe(){subscribed++}};const client={channel(){return channel},removeChannel(){removed++}};const doc={visibilityState:'hidden',addEventListener:(name,fn)=>docEvents.set(name,fn),removeEventListener:(name)=>docEvents.delete(name)};const win={addEventListener:(name,fn)=>winEvents.set(name,fn),removeEventListener:(name)=>winEvents.delete(name),setInterval:(fn,delay)=>{pollFn=fn;assert.equal(delay,20000);return 1},clearInterval:()=>{pollFn=null}};let refreshes=0,polls=0;const stop=watchTimetablePlan({client,actorScope:'actor',planId:'plan',onInvalidate:()=>refreshes++,onPoll:()=>polls++,environment:{document:doc,window:win}});assert.equal(subscribed,1);assert.deepEqual(handlers.map(x=>x.filter.filter),['id=eq.plan','id=eq.operating','id=eq.plan','id=eq.operating']);for(const row of [{id:'other',change_sequence:1},{id:'plan',change_sequence:2},{id:'operating',change_sequence:3}])handlers[0].callback({new:row});assert.equal(refreshes,2);pollFn();assert.equal(polls,0);doc.visibilityState='visible';docEvents.get('visibilitychange')();winEvents.get('focus')();pollFn();assert.equal(refreshes,4);assert.equal(polls,1);stop();assert.equal(removed,1);assert.equal(docEvents.size,0);assert.equal(winEvents.size,0);});
test('plan metadata mutation uses canonical command envelope',async()=>{const calls=[];const client={rpc(name,args){calls.push({name,args});return Promise.resolve({data:{plan:{id:'plan',name:'Renamed',state:'draft',metaRevision:2,changeSequence:2,targetStartDate:null,targetEndDate:null}},error:null})}};const service=createTimetablePlanService({client,actorScope:'actor'});const command={operation:'rename',planId:'plan',expectedMetaRevision:1,name:'Renamed',requestKey:'key'};const result=await service.mutatePlan(command);assert.equal(result.plan.metaRevision,2);assert.deepEqual(calls,[{name:'mutate_timetable_plan_v1',args:{p_command:command}}]);});
