import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const testDir = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(testDir, "..");

function read(relativePath) {
  return fs.readFileSync(path.join(root, relativePath), "utf8");
}

test("class schedule workspace keeps dedicated lesson-design page contract and editable builder shell", () => {
  const source = read("v2/src/features/operations/class-schedule-workspace.tsx");

  assert.match(source, /buildLessonDesignSnapshot/);
  assert.match(source, /buildLessonDesignSearchParams/);
  assert.match(source, /buildLessonDesignPageHref/);
  assert.match(source, /buildCurriculumWorkspaceHref/);
  assert.match(source, /const \[lessonDesignOpen, setLessonDesignOpen\] = useState\(false\)/);
  assert.match(source, /const \[selectedLessonSessionId, setSelectedLessonSessionId\] = useState\(""\)/);
  assert.match(source, /const \[lessonPlanDraft, setLessonPlanDraft\] = useState<Record<string, unknown> \| null>\(null\)/);
  assert.match(source, /const \[isLessonDesignSaving, setIsLessonDesignSaving\] = useState\(false\)/);
  assert.match(source, /const \[lessonDesignSaveError, setLessonDesignSaveError\] = useState\(""\)/);
  assert.match(source, /const lessonPlanDefaults = useMemo\(/);
  assert.match(source, /normalizeSchedulePlan\(lessonPlanDraft, lessonPlanDefaults\)/);
  assert.match(source, /buildSchedulePlanForSave\(normalizedLessonPlan, lessonPlanDefaults\)/);
  assert.match(source, /buildLessonDesignSnapshot\(selectedRow, data.textbooks, lessonPlanForSave\)/);
  assert.doesNotMatch(source, /const handleLessonDayToggle = useCallback\(/);
  assert.doesNotMatch(source, /DAY_OPTIONS\.map/);
  assert.doesNotMatch(source, /const handleLessonGlobalSessionCountChange = useCallback\(/);
  assert.match(source, /const handleLessonPeriodChange = useCallback\(/);
  assert.match(source, /const handleAddLessonPeriod = useCallback\(/);
  assert.match(source, /const handleRemoveLessonPeriod = useCallback\(/);
  assert.match(source, /const handleSaveLessonPlan = useCallback\(async \(\) => \{/);
  assert.match(source, /<Dialog open=\{lessonDesignOpen\} onOpenChange=\{handleLessonDesignOpenChange\}>/);
  assert.match(source, /<DialogContent className="flex h-\[92vh\] w-\[98vw\] max-w-\[1600px\] flex-col overflow-hidden gap-0 p-0 xl:h-\[94vh\]">/);
  assert.match(source, /2xl:grid-cols-\[minmax\(18rem,0\.85fr\)_minmax\(30rem,1\.35fr\)_minmax\(22rem,1fr\)\]/);
  assert.match(source, /function normalizeSelectedLessonMonthKeys\(/);
  assert.match(source, /options: \{ fallbackToDefault\?: boolean \} = \{\}/);
  assert.match(source, /if \(options\.fallbackToDefault === false\) \{/);
  assert.match(source, /return \[\] as string\[\];/);
  assert.match(source, /const toggleLessonMonthKey = \(monthKey: string\) => \{/);
  assert.match(source, /normalizeSelectedLessonMonthKeys\([\s\S]*?\{ fallbackToDefault: false \}/);
  assert.match(source, /if \(lessonDesignOpen && selectedClassId === requestedClassId\) \{/);
  assert.match(source, /const matchedRequestedSession =[\s\S]*filteredLessonSessions\.find\(\(session\) => session\.id === requestedSessionId\)/);
  assert.match(source, /setSelectedLessonSessionId\(requestedSessionId\)/);
  assert.match(source, /const scopedSession =[\s\S]*lessonDesignSnapshot\?\.sessions\.find\(\(session\) => session\.id === resolvedSessionId\)/);
  assert.match(source, /if \(scopedSession\?\.monthKey\) \{/);
  assert.match(source, /setSelectedLessonMonthKeys\(\[scopedSession\.monthKey\]\)/);
  assert.doesNotMatch(source, /if \(scopedSession\?\.periodId\) \{/);
  assert.doesNotMatch(source, /setSelectedLessonPeriodId\(scopedSession\.periodId\)/);
  assert.match(source, /setSelectedLessonPeriodId\("all"\)/);
  assert.match(source, /sessionId: ""/);
  assert.match(source, /buildCurriculumWorkspaceHref\(new URLSearchParams\(searchParams\.toString\(\)\)\)/);
  assert.match(source, /수업계획으로 돌아가기/);
  assert.match(source, /<div className="bg-background">\s*\{lessonDesignWorkspaceContent\}/);
  assert.doesNotMatch(source, /<div className="overflow-hidden rounded-3xl bg-background shadow-sm">/);
  assert.doesNotMatch(source, /id=\{LESSON_DESIGN_SECTION_IDS\.overview\}/);
  assert.match(source, /id=\{LESSON_DESIGN_SECTION_IDS\.periods\}/);
  assert.match(source, /id=\{LESSON_DESIGN_SECTION_IDS\.calendar\}/);
  assert.match(source, /id=\{LESSON_DESIGN_SECTION_IDS\.board\}/);
  assert.doesNotMatch(source, /role="tablist" aria-label="일정 생성 월 선택"/);
  assert.doesNotMatch(source, /formatLessonMonthTabLabel\(month\.label\)/);
  assert.match(source, /lessonMonthDetailsOpen/);
  assert.match(source, /renderLessonMonthSessionDetails\(periodSessions\)/);
  assert.match(source, /const periodSessions = filteredLessonSessions/);
  assert.match(source, /aria-expanded=\{isPeriodDetailsOpen\}/);
  assert.match(source, /\{isPeriodDetailsOpen \? "상세 닫기" : "상세 보기"\}/);
  assert.doesNotMatch(source, /const periodDetailLabel = periodSelectedSession/);
  assert.doesNotMatch(source, /periodDetailLabel/);
  assert.match(source, /월 추가/);
  assert.doesNotMatch(source, /생성 구간 추가/);
  assert.doesNotMatch(source, /periodIssue\?\.statusLabel/);
  assert.match(source, /월 선택/);
  assert.match(source, /모든 월 보기/);
  assert.doesNotMatch(source, /기본 월/);
  assert.doesNotMatch(source, /전체 범위/);
  assert.doesNotMatch(source, /<Button type="button" size="sm" variant="outline" onClick=\{\(\) => resetLessonDesignFilters\("all"\)\}>[\s\S]*?전체 범위[\s\S]*?<\/Button>/);
  assert.doesNotMatch(source, /aria-label="수업 일정 현황"/);
  assert.doesNotMatch(source, /기준 해제/);
  assert.match(source, /시작일/);
  assert.match(source, /종료일/);
  assert.match(source, /저장 중/);
  assert.match(source, /저장 전 확인/);
  assert.match(source, /일정 생성/);
  assert.match(source, /캘린더/);
  assert.match(source, /회차 목록/);
  assert.match(source, /이미지 저장/);
  assert.doesNotMatch(source, /buildLessonDesignWorkflowSteps/);
  assert.doesNotMatch(source, /lessonDesignWorkflowSteps\.map/);
  assert.doesNotMatch(source, /aria-current=\{step\.state === "current" \? "step" : undefined\}/);
  assert.doesNotMatch(source, /lessonDesignPageNavigatorSections\.map/);
  assert.doesNotMatch(source, /lessonDesignPageHeader/);
  assert.doesNotMatch(source, /renderLessonDesignWorkspaceHeaderContent/);
  assert.doesNotMatch(source, /truncate text-xl font-semibold text-foreground">\{selectedRow\?\.title \|\| "수업 설계"\}/);
  assert.doesNotMatch(source, /Tips Class Plan/);
  assert.doesNotMatch(source, /생성 일정 캘린더/);
  assert.doesNotMatch(source, /수업 일정 보드/);
  assert.doesNotMatch(source, /공개 공유/);
  assert.doesNotMatch(source, /수업 설계 작업 공간/);
  assert.doesNotMatch(source, /선택한 반의 수업계획·수업설계 데이터를 큰 작업 화면에서 검토합니다/);
  assert.doesNotMatch(source, /기본 설정과 생성 기간만 남긴 작업 화면/);
  assert.doesNotMatch(source, /왼쪽에서 일정 생성 범위를 정리하고, 오른쪽에서 캘린더와 회차 흐름을 바로 확인합니다/);
});
