const json = (schema: object) => ({ "application/json": { schema } });
const uuid = { type: "string", format: "uuid" };
const error = { type: "object", required: ["code"], properties: { code: { type: "string" }, sqlstate: { type: "string" } } };
const envelope = { type: "object", required: ["data", "error"], properties: { data: { type: ["object", "null"] }, error: { oneOf: [error, { type: "null" }] } } };
const responses = Object.fromEntries([200, 400, 401, 403, 404, 409, 413, 415, 422, 429, 503].map(code => [code, { description: code === 200 ? "Result envelope. An operation may be unknown or failed; inspect data.state." : "Typed failure. Never retry with a new operation key or switch to browser writes.", content: json(envelope) }]));
const classId = { name: "classId", in: "path", required: true, schema: uuid };
const ref = (name: string) => ({ $ref: `#/components/schemas/${name}` });
const state = { type: "object", required: ["state"], properties: { state: { const: "not_requested" } } };
const schemas = {
  WeeklySlot: { type: "object", required: ["id", "weekday", "startMinute", "endMinute"], properties: { id: { type: "string" }, weekday: { type: "integer", minimum: 0, maximum: 6 }, startMinute: { type: "integer", minimum: 0, maximum: 1439 }, endMinute: { type: "integer", minimum: 1, maximum: 1440 }, teacherId: { type: ["string", "null"] }, classroomId: { type: ["string", "null"] } } },
  Class: { type: "object", required: ["id", "name", "version", "weeklySlots", "weeklyScheduleComplete"], properties: { id: uuid, name: { type: "string" }, subject: { type: ["string", "null"] }, grade: { type: ["string", "null"] }, teacher: { type: ["string", "null"] }, room: { type: ["string", "null"] }, status: { type: "string" }, schedule: { type: ["string", "null"] }, version: { type: "string", pattern: "^[a-f0-9]{64}$", description: "Opaque fingerprint; compare equality only." }, weeklySlots: { type: "array", items: ref("WeeklySlot") }, weeklyScheduleComplete: { type: "boolean" } } },
  ClassPage: { type: "object", required: ["items", "page", "pageSize", "total"], properties: { items: { type: "array", items: ref("Class") }, page: { type: "integer" }, pageSize: { const: 20 }, total: { type: "integer" } } },
  Connection: { type: "object", required: ["apiVersion", "credentialId", "executor", "scopes", "classIds", "expiresAt", "timezone"], properties: { apiVersion: { const: "1" }, credentialId: uuid, executor: { type: "string" }, scopes: { type: "array", items: { type: "string" } }, classIds: { type: "array", items: uuid }, expiresAt: { type: "string", format: "date-time" }, timezone: { const: "Asia/Seoul" } } },
  Calendar: { type: "object", required: ["items", "from", "to"], properties: { from: { type: "string", format: "date" }, to: { type: "string", format: "date" }, items: { type: "array", items: { type: "object", properties: { id: uuid, title: { type: "string" }, date: { type: "string", format: "date" }, type: { type: ["string", "null"] }, schoolId: { type: ["string", "null"] }, grade: { type: ["string", "null"] } } } } } },
  Preview: { type: "object", required: ["previewToken", "expiresAt", "before", "after", "effect", "materializedLessonsChanged", "notifications"], properties: { previewToken: uuid, expiresAt: { type: "string", format: "date-time" }, before: ref("Class"), after: ref("Class"), effect: { const: "weekly_template_only" }, materializedLessonsChanged: { const: false }, notifications: state } },
  Operation: { type: "object", required: ["operationId", "state"], properties: { operationId: uuid, state: { enum: ["applied", "failed", "unknown"] }, class: ref("Class"), error, appliedAt: { type: "string", format: "date-time" }, replayed: { type: "boolean" }, retryWithNewKey: { const: false }, executor: { type: "string" }, actorProfileId: uuid, sourceReference: { type: ["string", "null"] }, requesterVerified: { const: false }, effect: { const: "weekly_template_only" }, materializedLessonsChanged: { const: false }, notifications: state, externalSync: state, reply: state } },
};
const responseFor = (name: string) => ({ ...responses, "200": { description: "Result envelope. Inspect the operation state before reporting completion.", content: json({ ...envelope, properties: { data: ref(name), error: envelope.properties.error } }) } });
export const agentOpenApi = {
  openapi: "3.1.0",
  info: { title: "TIPS Agent API", version: "1.0.0", description: "Scoped, revocable integration for class/calendar reads and ONE existing weekly slot's time change. Weekly templates only; this does not reschedule materialized lessons, create makeup lessons, or send messages. All dates/times use Asia/Seoul. The source reference is unverified context, never requester authorization." },
  servers: [{ url: "/api/v1" }],
  security: [{ agentBearer: [] }],
  components: { schemas, securitySchemes: { agentBearer: { type: "http", scheme: "bearer", bearerFormat: "tips_agent_<64 hex chars>" } } },
  paths: {
    "/health": { get: { operationId: "getAgentConnection", description: "Validate the credential. Returns API version, allowed scopes/class IDs, executor label, expiry and timezone.", responses: responseFor("Connection") } },
    "/classes": { get: { operationId: "listClasses", description: "Requires classes:read. items contain id/name/subject/grade/teacher/room/status/schedule/version/weeklySlots/weeklyScheduleComplete. No student, payment, note or enrollment records. Page size is 20; iterate until total is covered.", parameters: [{ name: "search", in: "query", schema: { type: "string", maxLength: 100 } }, { name: "status", in: "query", schema: { type: "string", enum: ["수강", "개강 준비", "종강"] } }, { name: "page", in: "query", schema: { type: "integer", minimum: 1, maximum: 10000, default: 1 } }], responses: responseFor("ClassPage") } },
    "/classes/{classId}": { get: { operationId: "getClass", description: "Requires classes:read. Use the exact id from search. version is an opaque schedule fingerprint. weeklySlots expose id, weekday (0=Sunday), startMinute, endMinute, teacherId, classroomId. An incomplete schedule cannot be edited.", parameters: [classId], responses: responseFor("Class") } },
    "/calendar/events": { get: { operationId: "listAcademicEvents", description: "Requires calendar:read. Academic event metadata only: id/title/date/type/schoolId/grade. This is not a complete class lesson calendar and does not claim to list all makeup/closure events. Date window maximum 31 days difference.", parameters: ["from", "to"].map(name => ({ name, in: "query", required: true, schema: { type: "string", format: "date" } })), responses: responseFor("Calendar") } },
    "/classes/{classId}/weekly-time/preview": { post: { operationId: "previewWeeklyTimeChange", description: "Requires schedule:preview and an explicit class grant. Checks the existing domain writer in a rolled-back subtransaction. Returns previewToken, expiry (10 minutes), before/after and effect=weekly_template_only. No business data or sends persist. A preview is not user approval. Only time changes of ONE existing weekly slot are supported.", parameters: [classId], requestBody: { required: true, content: json({ type: "object", additionalProperties: false, required: ["expectedVersion", "slotId", "startMinute", "endMinute", "reason"], properties: { expectedVersion: { type: "string", pattern: "^[a-f0-9]{64}$" }, slotId: { type: "string", maxLength: 160 }, startMinute: { type: "integer", minimum: 0, maximum: 1439 }, endMinute: { type: "integer", minimum: 1, maximum: 1440 }, reason: { type: "string", minLength: 1, maxLength: 300 } } }) }, responses: responseFor("Preview") } },
    "/operations": { post: { operationId: "commitWeeklyTimeChange", description: "Requires schedule:write. Commit an authorized preview, recheck grant, expiry, source version and conflicts under the existing lock. Persist request key BEFORE sending in your own journal. An exact replay returns the original outcome. Never generate a new key after a timeout. The same preview cannot be committed with another key. Successful data.state=applied includes the saved class and separate notifications/externalSync/reply states, all not_requested. Actor is the credential issuer; requesterVerified=false.", parameters: [{ name: "Idempotency-Key", in: "header", required: true, schema: uuid }], requestBody: { required: true, content: json({ type: "object", additionalProperties: false, required: ["previewToken"], properties: { previewToken: uuid, sourceReference: { type: "string", maxLength: 500, description: "Optional original request URL or opaque reference. No private message body, tokens, or personal data." } } }) }, responses: responseFor("Operation") } },
    "/operations/{requestKey}": { get: { operationId: "getOperation", description: "Requires schedule:write. Credential-scoped durable receipt lookup using the client-generated request key. state=unknown means no durable receipt was visible, NOT failed/not-applied. Do not issue another mutation on unknown; report unresolved. GET returns 200 for both applied and failed receipts; inspect data.state and error.", parameters: [{ name: "requestKey", in: "path", required: true, schema: uuid }], responses: responseFor("Operation") } },
  },
} as const;
