import { createImmediateNotificationAdapter } from "./immediate-notification-adapter.ts"

export const makeupRequestsNotificationAdapter = createImmediateNotificationAdapter({
  workflowKey: "makeup_requests",
  sourceTypes: ["makeup_request_event"],
  linkRoot: "/admin/makeup-requests",
  linkPayloadKey: "makeup_request_id",
  linkQueryKey: "request",
  eventLabels: {
    "makeup.submitted": "신청 제출",
    "makeup.refund_requested": "환불 신청",
    "makeup.approved": "결재 승인",
    "makeup.refund_completed": "환불 완료",
    "makeup.approval_canceled": "승인 취소",
    "makeup.revision_requested": "보완 요청",
    "makeup.rejected": "반려",
  },
  audienceProfileFields: {
    requester_profile: ["requester_profile_id"],
    approver_profile: ["approver_profile_id"],
    management_team: ["management_profile_ids"],
    executive_team: ["executive_profile_ids"],
    subject_team: ["subject_profile_ids"],
  },
  renderFields: {
    process: ["process"],
    status: ["status", "workflow_status"],
    class_name: ["class_name"],
    subject: ["subject"],
    teacher_name: ["teacher_name"],
    reason: ["reason"],
    cancel_date: ["cancel_date"],
    makeup_at: ["makeup_at"],
    makeup_room_spaced: ["makeup_room_spaced"],
    makeup_room: ["makeup_room"],
    requester_name: ["requester_name"],
    submitted_at: ["submitted_at"],
    revision_requested_at: ["revision_requested_at"],
    revision_reason: ["revision_reason"],
    approved_at: ["approved_at"],
    approval_note: ["approval_note"],
    rejected_at: ["rejected_at"],
    rejected_reason: ["rejected_reason"],
    canceled_at: ["canceled_at"],
    canceled_note: ["canceled_note"],
    approver_name: ["approver_name"],
    fallback_title: ["fallback_title"],
    fallback_body: ["fallback_body"],
  },
})
